### ISSUE TITLE
sol.markdown() converts nested lists to a single html list

### ISSUE THREAD

**Issue by prionkor** [widgetti/solara#12]
### Example: 

```md

- [What it is?](#what-it-is?)
- [Example](#example)
- [Usage](#usage)
- [Deployment](#deployment)
  - [Flask](#flask)
  - [Starlette](#flask)
  - [FastAPI](#flask)
  - [Voila](#voila)
  - [Panel](#panel)
  - [Nginx](#nginx)
- [Installation](#installation)
- [Development](#development)
- [FAQ](#faq)
```
### Converted to:

```html
<div class="solara-markdown rendered_html jp-RenderedHTMLCommon">
    <ul>
        <li><a href="#what-it-is?">What it is?</a></li>
        <li><a href="#example">Example</a></li>
        <li><a href="#usage">Usage</a></li> 
        <li><a href="#deployment">Deployment</a></li> 
        <li><a href="#flask">Flask</a></li> 
        <li><a href="#flask">Starlette</a></li> 
        <li><a href="#flask">FastAPI</a></li> 
        <li><a href="#voila">Voila</a></li> 
        <li><a href="#panel">Panel</a></li> 
        <li><a href="#nginx">Nginx</a></li> 
        <li><a href="#installation">Installation</a></li> 
        <li><a href="#development">Development</a></li> 
        <li><a href="#faq">FAQ</a></li>
    </ul>
</div>
```

It should output a nested list. The issue exists for ordered list as well.

This online markdown converter can be used to see appropriate output https://markdowntohtml.com/

**Comment by maartenbreddels** [comment]
Thanks @prionkor,

see https://github.com/Python-Markdown/markdown/issues/3 for a discussion on the topic.
This formally isn't valid markdown, it should have at least 3 spaces (according to the discussion 4). Though most implementations render this fine.
We could include the https://github.com/radude/mdx_truly_sane_lists extension which "fixes" this.
@mariobuikhuizen strong opinions on this?

**Comment by prionkor** [comment]
Note: 

Indentation 3 does not work. Indentation level 4 will work. We will need to add this in the documentation. I am closing this but we will need to remember this we write documentations.
