### ISSUE TITLE
solara.Sidebar() is not displayed

### ISSUE THREAD

**Issue by yugosuz** [widgetti/solara#125]
Thank you for the great product.
I have updated from version 1.14.0 to 1.15.0 and solara.Sidebar() is no longer displayed.
Below is the result of running the same code on versions 1.14.0 and 1.15.0.

code:
```
import solara
import solara.lab

github_url = solara.util.github_url(__file__)

@solara.component
def Page():
    with solara.Column() as main:
        with solara.Sidebar():
            solara.Markdown("## I am in the sidebar")
            solara.SliderInt(label="Ideal for placing controls")
        solara.Info("I'm in the main content area, put your main content here")
    return main
```

result 1.14.0
![Screenshot 2023-05-28 at 15 26 30](https://github.com/widgetti/solara/assets/105782424/f35865a2-2571-479c-a04d-681082ef1a54)
result 1.15.0
![Screenshot 2023-05-28 at 15 21 00](https://github.com/widgetti/solara/assets/105782424/abc24d65-7aec-4797-b0d0-57db1219cd6b)

**Comment by Ben-Epstein** [comment]
+1 seeing the same issue, just upgraded to 1.15.0

Seeing this on my branch to incorporate tabs: https://github.com/Ben-Epstein/solara-examples/commit/2efeb4f01193ec986318d96e0095440dd1277f44

<img width="1680" alt="Screenshot 2023-05-28 at 5 19 33 PM" src="https://github.com/widgetti/solara/assets/22605641/6d47cd93-1a39-4d14-871a-70a8e9325d88">

**Comment by maartenbreddels** [comment]
Thank for reporting, I will this as soon as I can!
