### ISSUE TITLE
Quickstart tutorial and Solara Server fails with "no session cookie" on Safari

### ISSUE THREAD

**Issue by jfoster17** [widgetti/solara#133]
Following the [Quickstart example](https://solara.dev/docs/quickstart) when I try to run the application in solara server as `solara run sol.py`, it does not work in Safari, although it does work in Chrome and Firefox. Safari reports

> ERROR:    no session cookie

at the terminal and

> [Error] WebSocket connection to 'ws://localhost:8765/jupyter/api/kernels/solara-id/channels?session_id=84fac001-b905-413b-b3d8-116e5c1d88cc' failed: There was a bad response from the server.

at the javascript console. 

This is with Safari 16.4.1. This is possibly nothing to do with Solara, and might be [this bug](https://bugs.webkit.org/show_bug.cgi?id=255524).

Running the application from within Jupyter Lab works just fine in all browsers I tested.

**Comment by maartenbreddels** [comment]
Thank you Jonathan for the report, I'll look into it!
