### ISSUE TITLE
[Enhancement] Select widget missing keyword disabled

### ISSUE THREAD

**Issue by lp9052** [widgetti/solara#144]
Select and SelectMultiple widgets seem missing keyword disabled.

Is it by design or still under implementation?

Is there any work around instead of using ipyvuetify directly.

thanks!

**Comment by maartenbreddels** [comment]
Hi,

we still need to add it. Should be easy to add in https://github.com/widgetti/solara/blob/7ec459c4d9f8e65ede0f24301da695cb7bcff8d1/solara/components/select.py#L14

Or otherwise use that code as an example (ignore all the type stuff).

Hope that helps.

Regards,

Maarten
