### ISSUE TITLE
support offline mode

### ISSUE THREAD

**Issue by yuuuxt** [widgetti/solara#147]
It would be nice to have an offline mode that enables pure offline usage. (seems some js files are not packed right now)

**Comment by maartenbreddels** [comment]
Hi,

did you install solara-assets? I guess you are referring the the failing fetch of mermaid?

Regards,

Maarten

**Comment by yuuuxt** [comment]
Thanks for the update (I didn't notice the existence of this package)! After installation I'm able to run it in notebook now (with the click example; though it fails in browser, but should be another issue).
