### ISSUE TITLE
No clear way to define dark theme

### ISSUE THREAD

**Issue by hkayabilisim** [widgetti/solara#156]
When I look at the solara output, I see that it is possible to define "theme--dark" in most widgets (see below). However, I couldn't find a programmatic way to set the theme in solara. Is it possible to set theme of widgets in a Page with a single statement from Python?

![image](https://github.com/widgetti/solara/assets/2515171/45a173b6-5354-426c-b23c-86d47afe5266)

**Comment by maartenbreddels** [comment]
Hi Huseyin,

There is not API for changing the theme programmatically in Solara yet, although I could probably make a workaround if you really need it.
Instead, if you check:
```
$ solara run --help
...
│  --theme-variant                THEMEVARIANT                 Use light or dark variant,    │
│                                                              or auto detect (auto).        │
│                                                              [default: light              
...
```

Which means you can select a dark theme using:
```
$ solara run --theme-variant=dark sol.py
```

I hope this helps you!

Regards,

Maarten

**Comment by maartenbreddels** [comment]
TODO: This needs proper documentation

**Comment by hkayabilisim** [comment]
"solara run --theme-variant dark"  solves my issue right now. No need for extra coding, thank you very much for the information.
