### ISSUE TITLE
Slider state value not getting updated

### ISSUE THREAD

**Issue by RaviNaik** [widgetti/solara#165]
Hi,

I'm facing issue with the `solara.SliderRangeInt`. The state value attached to slider is not getting updated on changing the slider value on the UI. For ex, in the code below it always prints the initial state values. Please let me know how to resolve this.

Reference code:
```
import solara

@solara.component
def Page():
    with solara.Column():
        solara.Title("My Dashboard")
        with solara.Sidebar():
            years_selected, set_year = solara.use_state((1955, 2000))
            solara.SliderRangeInt(label="Please Select Year",
                                  value=years_selected,
                                  min=1950,max=2023,
                                  step=1,thumb_label="always")
            print(years_selected)
```

**Comment by maartenbreddels** [comment]
Hi,

you have to either use a reactive variable, or attach respond to changes in the slider: `on_value=set_year`.
In Python, by passing an integer, the receiving component cannot mutate it, does that make sense?

Regards,

Maarten

**Comment by RaviNaik** [comment]
Tried both the approaches, working now. Thanks @maartenbreddels 👍 👍
