### ISSUE TITLE
Latex example does not work in solara 1.17.5

### ISSUE THREAD

**Issue by kolibril13** [widgetti/solara#175]
I have a small bug to report:
I've just tried to copy+paste this latex example https://solara.dev/api/markdown, but it does not seem to work on the latest Solana version:
![image](https://github.com/widgetti/solara/assets/44469195/08cfbd66-48c3-4367-aa18-2cd530f1db61)

**Comment by maartenbreddels** [comment]
Thanks for the report, 

Weird thing is that after running:

```python
from IPython.display import Math
Math(data='E \sim mc^2')
```
It does work, which means that `window.MathJax` is only available after some mathjax extensions/bundle/chunk is loaded in the notebook.

**Comment by kolibril13** [comment]
Indeed, that's weird, your example also works on my machine.
Don't know if you know about https://katex.org/, maybe that's an alternative.

**Comment by maartenbreddels** [comment]
Yes, but I prefer to stay close to ipywidgets/jupyter, which uses mathjax.

**Comment by maartenbreddels** [comment]
or do you see strong reasons to switch, and do you know if it is compatible?

**Comment by kolibril13** [comment]
I recently read an article that mentioned katex as alternative fast latex renderer.
But I see that it makes total sense to stay with the ipywidgets default mathjax option.

**Comment by iisakkirotko** [comment]
Hi! Just to update the conversation here as well, it seems like https://github.com/jupyter-widgets/ipywidgets/pull/3847 fixes this issue in ipywidgets, so perhaps we can continue developing on their success.
