### ISSUE TITLE
Doc fails to render at `https://solara.dev/api/dataframe`

### ISSUE THREAD

**Issue by gab23r** [widgetti/solara#176]
Screenshot from my browser:

![image](https://github.com/widgetti/solara/assets/106454081/6b0dd71d-7e56-431b-a066-ef31ad8cb973)

Thank you for you work !

**Comment by maartenbreddels** [comment]
Thank you, fixed in c58f61be3de62b04f9eae1c53faeea898ee2a4b3  see also https://github.com/widgetti/solara/issues/201
