### ISSUE TITLE
Reload + Polars not working

### ISSUE THREAD

**Issue by Lundez** [widgetti/solara#177]
Hi!

Polars (DataFrame) is built using Rust-bindings and this doesn't seem to work with Solara "Auto-Reload" function.

After first reload I get `NameError: name 'PyDataFrame' is not defined`, I believe because it's not reloading the imports correctly.
Because Polars uses rust it's using PyO3 to bind into Rust.

It's hard to debug as I don't understand Solara in-depth yet.
This works in streamlit.

How to reproduce:
```python
import solara
import polars as pl

@solara.component
def Page():
    file, set_file = solara.use_state(None)
    solara.FileDrop(on_file=set_file, lazy=False)
    solara.Text(f"Hello World!")
    Page2(file)

@solara.component
def Page2(file):

    if file is not None:
        solara.Text(f"File")
        df = pl.read_csv(file["data"])
        solara.DataFrame(df.to_pandas())
    else:
        solara.Text("No file, please upload one.")
```

Change a line and try to load a CSV again and it'll fail.. :/
Works on first try after starting server

Additionally I get a warning `Warning: polars binary missing!` which seems to suggest Rust bindings failing.

**Comment by maartenbreddels** [comment]
Hi Lundez,

thanks for opening the issue. This is related to https://github.com/widgetti/solara/issues/148
I hope to take a look at this soon, or at least provide a workaround.

Thank you,

Maarten

**Comment by Lundez** [comment]
@maartenbreddels if I add `polars` to the ignored reloaded imports (`reload.py`), e.g.
```python
reload_modules = {
            k for k in set(sys.modules) - set(self.ignore_modules) if not (k.startswith("solara.server") or k.startswith("anyio") or k.startswith("pandas") or k.startswith("polars"))
        }
```

it works!

**Comment by Lundez** [comment]
Just to keep things both trackable (GitHub) and in more private discussions (Discord) I share our discussion here.

Lundez
> @MaartenBreddels i found that if we don't reload polars everything works as expected. I see pandas is excluded in the list (along with more libs), as such I did the same with polars. Posted this in issue.
>
> I went further and was thinking, what modules do we wish to reload? Perhaps we can only reload modules from our cwd (i.e. sys.path[0])? Why would we want to reload dependencies?

Marten
> @Londet i have that way of reloading now locally, because I also ran into issues. I think that should be the default for reloading from now on. Great we reach similar conclusions 🙂 I'd like to compare to streamlit as well btw, because looking at their code, I think they also reload everything.
