### ISSUE TITLE
`GridDraggable` on the Solara documentation has an Error

### ISSUE THREAD

**Issue by theeldermillenial** [widgetti/solara#201]
The Solara API documentation has an error when trying to load the `GridDraggable` documentation.

https://solara.dev/api/griddraggable

![image](https://github.com/widgetti/solara/assets/123320130/dbed6373-42fb-443e-995d-1976bfa72d32)

**Comment by trexdbg** [comment]
Same issue for dataframe documentation.
https://solara.dev/api/dataframe

**Comment by maartenbreddels** [comment]
Thank you, this is now fixed (see c58f61be3de62b04f9eae1c53faeea898ee2a4b3)
