### ISSUE TITLE
Add a menu widget

### ISSUE THREAD

**Issue by lp9052** [widgetti/solara#215]
We shall have a menu component. Now the similar behavior is archived through sidebar. Sometime menu is more intuitive to use and more compact to show. Also it's a building block for other widgets such datpicker.

**Comment by iisakkirotko** [comment]
Hi @lp9052,

We might add support for this in the future. In the meantime, you can use the vuetify [menu component](https://v2.vuetifyjs.com/en/components/menus/#api). For more info on how to do that, see [here](https://solara.dev/docs/understanding/ipyvuetify).

**Comment by iisakkirotko** [comment]
Should have mentioned this issue in the PR, but this was added in https://github.com/widgetti/solara/pull/295, and is available as `solara.lab.Menu/ContextMenu/ClickMenu` with solara `v1.21`
