### ISSUE TITLE
What happened to Switch?

### ISSUE THREAD

**Issue by stepsbystep** [widgetti/solara#221]
I'm new to solara and experimenting, now by taking a streamlit project and changing the front end. Streamlit has these expandable containers. Looking at the online API documentation, Switch looked like an easy way to mimmick this functionality. The following code is based on the Switch example, but when I run it, I get the message that the solara module does not contain Switch: 

```
            solara.Switch(label="For more information .turn on the switch", value=show_more)
            if show_more.value:
                solara.Markdown(f"This chart shows ... ")
```
Am I doing something wrong? I'm running version 1.19. So far everything else is working pretty well. 

If Switch is no longer available, can you recommend an alternative approach? I tried using Button to set show_more, but while the button seems to work, I haven't figured out the real time framework very well yet.

**Comment by maartenbreddels** [comment]
Hi,

I think something went wrong, because it is included in 1.19. Can you print out `solara.__version__`, and maybe `dir(solara)`

Your original problem can be solved using `Details`.

```python
@solara.component
def Page():
    with solara.Details(summary='More options'):
        solara.Switch(label="Turbo mode")
        solara.Markdown("Hello")
```

Which seems not to be documented! 🤦 

Your approach seems like a good workaround, but I think something is off with your installation.

Regards,

Maarten

**Comment by stepsbystep** [comment]
Thanks Maarten, that's great ... Details! That should hold me for a while.

As for Switch, my virtual env wasn't set up properly. I was still in 1.175 in that directory.

Best wishes,

Barry

**Comment by maartenbreddels** [comment]
Good to hear! Join us on discord if you have something you want to show!
