### ISSUE TITLE
image component with mouse click?

### ISSUE THREAD

**Issue by JunchuanYu** [widgetti/solara#228]
Translation into English: Can Solara achieve the functionality of clicking on an image and instantly returning the coordinates (x, y) of the clicked location, while also displaying a red dot at the clicked point?

Are there any examples to refer to? Can anyone tell me how to achieve this?

**Comment by Cr33pyGuy** [comment]
Hi @JunchuanYu !

This is possible to do using `solara.v.use_event()` (since yesterday). We also have to use `solara.Div` as a container for `solara.Image`, since `solara.Image` doesn't support `use_event` directly. Here is an example:

```python
import solara

image_source = "https://images.unsplash.com/photo-1575936123452-b67c3203c357"

#This component will render the image. It's separated from the other one due to a bug in Reacton (see https://github.com/widgetti/reacton/issues/14)
@solara.component
def Content(src, coordinate_list: solara.Reactive[list]):
    #We have to use a solara.Div container for the image element, because solara.Image does not support the use of use_event.
    img = solara.Div(children=[solara.Image(src)])

    #Adds newest click coordinates to the end of coordinate_list
    def click_finder(widget, type, details):
        coordinate_list.set([*coordinate_list.value, [details['offsetX'], details['offsetY']]])
    
    #Monitors events on the element img
    solara.v.use_event(img, 'click', click_finder)

@solara.component
def ImgCoordinates(src):
    #This will be a list of lists, where each sub-list is a pair of coordinates
    coordinate_list = solara.use_reactive([])

    #Draws circle at coordinates circleX, circleY
    def circle(circleX, circleY):
        css = "border: solid red 5px; border-radius: 50%; position: absolute; left:" + str(circleX - 5) + "px; top:" + str(circleY - 5) + "px;"
        solara.HTML(tag = "div", unsafe_innerHTML="", style=css)

    #A component that displays the string str (will contain the coordinates of the last click)
    def coord_display(str):
        solara.Text(str, style="position:absolute; top: 0; left: 0;display: block;")
    
    Content(src, coordinate_list)
    
    #Display last clicked coordinates, if non-empty
    if coordinate_list.value:
        string = "[ " + str(coordinate_list.value[-1][0]) + " , " + str(coordinate_list.value[-1][1]) + " ]"
        coord_display(string)
    else:
        coord_display("")

    #Draw circles for every set of coordinates clicked.
    for coordinates in coordinate_list.value:
        circle(coordinates[0], coordinates[1])

#Make page
@solara.component
def page():
    ImgCoordinates(image_source)
```

Note that **ipyvue** version **1.10.0** is needed for this solution to work.

**Comment by JunchuanYu** [comment]
Hi@Cr33pyGuy！

Thank you for your detailed response. I tried to rerun your code, but I always failed. I updated Solara and IPyVue, but I still get the following error message:

Traceback (most recent call last):
  File "c:\ProgramData\Anaconda3\envs\py36\lib\site-packages\reacton\ipyvue.py", line 23, in handler
    callback_ref.current(*args)
  File "<ipython-input-1-b3cb194c6e5f>", line 13, in click_finder
    coordinate_list.set([*coordinate_list.value, [details['offsetX'], details['offsetY']]])
KeyError: 'offsetX'

**Comment by Cr33pyGuy** [comment]
The error should be due to having the old version of ipyvue. If you've updated your install, make sure to empty cache and hard reload in your browser, since the old JavaScript might still be cached. Let me know if that works.

**Comment by JunchuanYu** [comment]
> The error should be due to having the old version of ipyvue. If you've updated your install, make sure to empty cache and hard reload in your browser, since the old JavaScript might still be cached. Let me know if that works.

It works! thank you! 😊@Cr33pyGuy！
