### ISSUE TITLE
Plotly Figure for Image Annotations

### ISSUE THREAD

**Issue by itepifanio** [widgetti/solara#249]
Plotly offers [image annotations features](https://dash.plotly.com/annotations). I'm building a semi automatic annotator using solara and to allow user to update the annotations I need to listen to the `relayoutData` event, an option that the solara's component doesn't offer.

![Screenshot from 2023-08-21 15-45-33](https://github.com/widgetti/solara/assets/6730205/1dc14c7b-75a7-48c3-bab7-9b4011c1047d)

I just create my custom component, but the ability to listen to `relayoutData` may be a interesting feature to add to solara. My current code:

```python
@solara.component
def FigurePlotly(
    fig,
    on_canvas_callback: Optional[Callable[[Any], None]] = None,
    dependencies=None,
):
    from plotly.graph_objs._figurewidget import FigureWidget

    fig_element = FigureWidget.element(on__js2py_relayout=on_canvas_callback)

    def update_data():
        fig_widget = solara.get_widget(fig_element)
        fig_widget.layout = fig.layout

        fig_widget.add_traces(fig.data)

    solara.use_effect(update_data, dependencies or fig)
    return fig_element
```

**Comment by maartenbreddels** [comment]
Hi,

thanks for opening the issue!
I think this would be great to support solara itself. I think keeping adding a `on_relayout` callback, possibly with an example would be very valuable.
Do you want to open a PR for this?

Regards,

Maarten
