### ISSUE TITLE
Continuous Update for solara Slider

### ISSUE THREAD

**Issue by itepifanio** [widgetti/solara#262]
[Continuous update feature](https://ipywidgets.readthedocs.io/en/stable/examples/Using%20Interact.html#continuous-update) from ipywidgets are great to avoid additional processing when interacting with the UI.

Solara uses ipyvuetify which doesn't seem to have the continuous update feature but it [has a workaround](https://github.com/widgetti/ipyvuetify/issues/25)

**Comment by maartenbreddels** [comment]
Hi Ítalo,

although I think solara is a good place to implement this workaround, so we can have it for our slider, I was wondering if you thought about using [use_thread](https://solara.dev/api/use_thread). If use_thread depends on the slider value, the previous calculation/processing can/will be cancelled.

Would that work for you?

Regards,

Maarten

**Comment by itepifanio** [comment]
> Would that work for you?

Thanks for the tip! I wasn't considering `use_thread` usage, it should work
