### ISSUE TITLE
Getting bounds of visible area of an ipyleaflet.Map.element

### ISSUE THREAD

**Issue by hkayabilisim** [widgetti/solara#264]
Hi,

Is it possible to get the bound of a map whenever it changes? Similar to on_zoom or on_center functionality like below.

bound, set_bound = solara.use_state(None)
zoom, set_zoom = solara.use_state(10)

ipyleaflet.Map.element(...
    zoom=zoom,
    on_zoom = set_zoom,
    on_bound_change = set_bound
)

**Comment by Cr33pyGuy** [comment]
Hi @hkayabilisim,

This should be possible. Would using `on_bounds`, i.e.

```python
ipyleaflet.Map.element(center=center, zoom=zoom, on_zoom=set_zoom, on_bounds=set_bound)
```

work for your purposes?

**Comment by hkayabilisim** [comment]
Thank you @Cr33pyGuy! You saved my life :) How did you find it? I have been looking for hours.

**Comment by Cr33pyGuy** [comment]
I had a look through the ipyleaflet code, from where you can see that `bounds` is a traitlet, which means that there should be an `on_bounds` callback associated to it (see [here](https://traitlets.readthedocs.io/en/stable/), for instance). I have to admit I got some help from @maartenbreddels too :)

**Comment by hkayabilisim** [comment]
Thank you @Cr33pyGuy again!

In case someone bumps into this, I've added on_bounds feature to the ipleaflet example on the webpage: 
PR: https://github.com/widgetti/solara/pull/270
