### ISSUE TITLE
Cannot switch to dark mode

### ISSUE THREAD

**Issue by Jhsmit** [widgetti/solara#296]
running an app with the option `theme-variant` should enable dark theme, but this does not work for me.
Clean install on win11, reproduced by @mariobuikhuizen 

```
$ solara run --theme-variant dark script.py
```

Issue #156 suggests that it did work in previous versions

**Comment by Ranger11Danger** [comment]
@Jhsmit  i'm having this problem too and found a work around until its fixed
if you goto where your python library is intalled `/home/<username>/.local/lib/<python version>/site-packages/solara/server`
there is a file `settings.py` on line 33 you can change `variant: ThemeVariant = ThemeVariant.light` -> `variant: ThemeVariant = ThemeVariant.dark` to make it default to dark

**Comment by maartenbreddels** [comment]
This should be fixed in v1.20.0
