### ISSUE TITLE
FileBrowser does not render correctly in jupyter lab

### ISSUE THREAD

**Issue by Jhsmit** [widgetti/solara#32]
The `solara.FileBrowser` appears to be functional but does not render correctly:

![image](https://user-images.githubusercontent.com/7881506/223707630-e38ad956-f83e-4f3f-96b8-44cebb0dae80.png)

This is using jupyter lab on firefox

**Comment by maartenbreddels** [comment]
Thanks for the report Jochem, this is fixed in 1.8.0
