### ISSUE TITLE
Periodic Updates in Solara?

### ISSUE THREAD

**Issue by prappleizer** [widgetti/solara#327]
Hello, 

Not sure if this is a feature request or needed advice, but I'm wondering if there is any ability to have a solara webapp execute periodic updates for certain components. For example, my use case is a "countdown clock" which indicates how many hours/minutes remain until sunrise (or some other specified time) --- I would like this specific component view to update ~once/second to be a live view for the user (ideally only certain components need this continuous callback, while others rely on, e.g., a user interaction to trigger an event). 

In holoviz/panel this is explicitly called a periodic callback. Does such a similar feature exist (perhaps by another name) in Solara? (I wasn't able to find something in the docs). 

If it does not exist, would it be challenging to implement? (either by me as a custom component, or as a feature of solara?) 

Thanks!

**Comment by itepifanio** [comment]
Check this [Timer example](https://github.com/iisakkirotko/Solara7GUIs/blob/main/4%20Timer/timer.ipynb), it uses `use_thread` to do a countdown component as well.

**Comment by prappleizer** [comment]
Thanks @itepifanio! This seems very close to what I need; I believe I will be able to modify it to my purposes. Cheers.

**Comment by maartenbreddels** [comment]
See also https://solara.dev/examples/general/live_update and we had this hook on our discord:

```python
def use_interval(f: Callable, interval: float = 10.0, enabled=True):
    """
    Call a function periodically.

    Parameters
    ----------
    f
        Function to call periodically.
    interval
        Interval in milliseconds.
    """

    def run():
        if enabled:
            time_start = time.time()
            next_tick = time_start + interval
            while True:
                # instead of sleeping for 1 second, we sleep until the next second
                # this takes into account overhead and makes the timer more accurate
                f()
                time.sleep(max(0, next_tick - time.time()))
                next_tick += interval

    return solara.use_thread(run, dependencies=[interval, enabled])
```

which can be used like this:
```python
@solara.component
def Page():
    with solara.Column():
        solara.Title("Live Price Tracker")
        if State.updated.value:
            solara.Text(f"Last updated: {State.updated.value.strftime('%Y-%m-%d %H:%M:%S')}")
        Stock()

    # Periodically update data
    result = use_interval(State.fetch_latest_data, interval=3)  # Update every 3 seconds
    if result.error:
        raise result.error
```
