### ISSUE TITLE
Feature request: InputTextarea

### ISSUE THREAD

**Issue by alonsosilvaallende** [widgetti/solara#343]
I wonder if it makes sense to add an InputTextarea beside the InputText. It is relatively easy to do but perhaps it's helpful for new users coming from Streamlit.

<img width="1227" alt="Screenshot 2023-10-25 at 21 39 05" src="https://github.com/widgetti/solara/assets/30263736/e043f606-ed31-4138-9c38-9b12d1610547">

I can try to add what I have but it needs to be improved.

**Comment by iisakkirotko** [comment]
Hi @alonsosilvaallende!

Looking at https://github.com/widgetti/solara/pull/341 it seems we are just half step behind you.
