### ISSUE TITLE
Discord link broken

### ISSUE THREAD

**Issue by langestefan** [widgetti/solara#406]
The discord link is invalid.

**Comment by maartenbreddels** [comment]
Hi Stefan,

thank you for letting us know! I've update the URL that https://discord.solara.dev/ points to, I'll also update the rest.
This time I really really really created a discord link that does not expire (cc @iisakkirotko)

cheers,

Maarten

**Comment by langestefan** [comment]
Fixed, it works now. Thanks for the great talk today at pydata
