### ISSUE TITLE
clearing cdn cache directory

### ISSUE THREAD

**Issue by Jhsmit** [widgetti/solara#41]
Ok, mystery solved. You have to nuke your cdn cache directory, e.g. sth like this:
```
$ rm -rf /c/ProgramData/Miniconda3/envs/solara39/share/solara/cdn/
```

_Originally posted by @maartenbreddels in https://github.com/widgetti/solara/issues/37#issuecomment-1462164964_

I just updated my solara 1.7.1 to solara 1.8.0 (both installed with poetry), and I had to manually clear the cache dir to get the new install of solara to work.
Is it possible to automatically clear the cache with a new (minor) version install?

**Comment by maartenbreddels** [comment]
Hmm, IIRC we only need to make sure that if we want to write a file, that is currently a directory, we delete that directory. Thanks for reporting this!
