### ISSUE TITLE
Invalid Discord link

### ISSUE THREAD

**Issue by k1lgor** [widgetti/solara#424]
The invitation discord link is invalid and probably expired.
![image](https://github.com/widgetti/solara/assets/65338982/80f0b723-927d-46a6-93d7-4c150cb205cd)

**Comment by iisakkirotko** [comment]
Hi @k1lgor!

Where did you find this link? For me the one on the website works fine.

**Comment by k1lgor** [comment]
Found it in the `README.md` file.

**Comment by iisakkirotko** [comment]
Thanks for catching that. Should be fixed by https://github.com/widgetti/solara/commit/45e09d0ee402d1cdb6cd947feade7edca3101ebe .
