### ISSUE TITLE
UI disabled (greyed out) when view width < 960 px and sidebar open 

### ISSUE THREAD

**Issue by johanez** [widgetti/solara#437]
The standard layout sidebar does not work with **view width < 960 px** (medium breakpoint): when the sidebar is open, the whole interface gets disabled (grey semi transparent overlay), and the only interaction possible is clicking anywhere to close the sidebar.

This issue also affects the solara.dev examples e.g. [https://solara.dev/apps/layout-demo](https://solara.dev/apps/layout-demo).
To reproduce, set the view width < 960 px and open the sidebar.  

It worked for me earlier, but not with current stable solarea ( `1.25.0`). I didn't test earlier versions.

Tested with up to date Chrome and Firefox on Linux and Android.

(great work btw, thanks for this project!)

**Comment by iisakkirotko** [comment]
Should be fixed in version `1.25.1`

**Comment by johanez** [comment]
Thanks for the quick fix! :+1:
