### ISSUE TITLE
Automatically redirect to Oauth login

### ISSUE THREAD

**Issue by jonomon** [widgetti/solara#438]
Hello, 

I'm looking at the Oauth documentation (https://solara.dev/docs/enterprise/oauth) and the recommended approach to open the oauth dialog is:
```
@solara.component
def Page():
    if not auth.user.value:
        solara.Button("Login", icon_name="mdi-login", href=auth.get_login_url())
    else:
        userinfo = auth.user.value['userinfo']
        if 'name' in userinfo:
            solara.Markdown(f"### Welcome {userinfo['name']}")
        solara.Button("Logout", icon_name="mdi-logout", href=auth.get_logout_url())
```

I was wondering if it's possible to automatically open the auth dialog without the user pressing a button?

Something along the lines of:

```
@solara.component
def Page():
    if not auth.user.value:
        router = solara.use_router()
        router.push(auth.get_login_url())
    else:
        # do something
```
When I tried the above, I get a "page not found error"

Thank you very much

**Comment by maartenbreddels** [comment]
Awesome :)
Can we improve the documentation on this? Maybe you can give us ideas where to improve things.
