### ISSUE TITLE
embedding as iframe does not fully render components

### ISSUE THREAD

**Issue by havok2063** [widgetti/solara#443]
Trying to embed Jdaviz as an iframe does not render correctly.  It renders mostly ok directly with `solara run`, but the bulk content does not render when embedded.  Am I missing some set up?  

Vue Solara component
```
<template>
    <div>
        <iframe src="http://localhost:8765" width="100%" height="500px"></iframe>
    </div>
</template>
```
Usage:
```
        <v-row>
            <v-col md="12">
                <Solara></Solara>
            </v-col>
        </v-row>
```

Embed Screenshot:
<img width="1645" alt="Screen Shot 2024-01-04 at 10 39 05 AM" src="https://github.com/widgetti/solara/assets/1836302/871f5daa-d24f-4ab1-8a9b-5639479601d4">

Solara Screenshot:
<img width="1647" alt="Screen Shot 2024-01-04 at 9 35 49 AM" src="https://github.com/widgetti/solara/assets/1836302/29df50b1-b9a7-4ac4-aa1b-39c642d9ffe5">

**Comment by maartenbreddels** [comment]
Hi Brian,

I've not been able to reproduce this, using the script I used when visiting STScI:
```
import solara




@solara.component
def Page():
    from jdaviz import Imviz
    import ipysplitpanes
    import ipygoldenlayout
    from jdaviz.app import custom_components
    import os
    import ipyvue
    import jdaviz

    ipysplitpanes.SplitPanes()
    ipygoldenlayout.GoldenLayout()
    for name, path in custom_components.items():
        ipyvue.register_component_from_file(None, name,
                                            os.path.join(os.path.dirname(jdaviz.__file__), path))

    ipyvue.register_component_from_file('g-viewer-tab', "container.vue", jdaviz.__file__)

    import tempfile
    imviz = Imviz()
    data_dir = tempfile.gettempdir()
    files = ['jw02727-o002_t062_nircam_clear-f090w_i2d.fits',
            #'jw02727-o002_t062_nircam_clear-f150w_i2d.fits',
            #'jw02727-o002_t062_nircam_clear-f200w_i2d.fits',
            'jw02727-o002_t062_nircam_clear-f277w_i2d.fits',
            #'jw02727-o002_t062_nircam_clear-f356w_i2d.fits',
            #'jw02727-o002_t062_nircam_clear-f444w_i2d.fits'
            ]

    for fn in files:
        uri = f"mast:JWST/product/{fn}"
        from astroquery.mast import Observations
        result = Observations.download_file(uri, local_path=f'{data_dir}/{fn}')
        imviz.load_data(f'{data_dir}/{fn}')
    # display(imviz.app)
    with solara.Column(children=[imviz.app]):
        pass
```

I can embed this within an iframe without issues.
Do you have more details for me, which version of solara, what code you run etc? Or a minimal reproducible example?

Regards,

Maarten

**Comment by havok2063** [comment]
@maartenbreddels ahh yes, I had the following solara page and forgot to add the custom `register_component` logic.  Adding that back in fixes the issue.  I guess this extra logic fixes some issue about use within iframes?   I'm running Solara 1.25.1.   

I think Solara is also forcing a dark theme on some Jdaviz styles.  @mariobuikhuizen identified an issue with Solara not recognizing Jdaviz's StyleRegistry.  

```
import solara


@solara.component
def Page():
    with solara.Column():
        from jdaviz import Specviz

        filename = '/Users/Brian/Work/sdss/sas/sdsswork/bhm/boss/spectro/redux/v6_0_6/spectra/lite/017057/59631/spec-017057-59631-27021598108289694.fits'

        spec = Specviz()
        spec.load_data(filename, format='SDSS-V spec multi')
        display(spec.app)
```

**Comment by havok2063** [comment]
This can be closed now.
