### ISSUE TITLE
`use_state_or_update` API docs source doesn't show `use_state_or_update` example code

### ISSUE THREAD

**Issue by Jhsmit** [widgetti/solara#45]
On the `use_state_or_update` API docs (https://solara.dev/api/use_state_or_update), when clicking the 'show code' button, you only see the code of the `Page` component, which doesn't use `use_state_or_update` at all. 

I guess this is because the api docs page is autogenerated from the `Page` component, which for most cases should be fine, however in this case the other components have the actual use case and information needed to understand the example. 

Suggestion: a button that links to the `github pages/api/ ... ` and/or a button that links to the solara implementation on GitHub

**Comment by maartenbreddels** [comment]
I agree, we'll just link to github!
