### ISSUE TITLE
Formula symbols

### ISSUE THREAD

**Issue by liebsc21** [widgetti/solara#466]
Is there an overview that shows which objects support rendering of (LaTex) symbols?

I read that [Markdown](https://solara.dev/api/markdown) can be used, but I am looking for a way to label InputFloat and Button with formula symbols which does not seem to be supported.

Btw, #175 can be closed, couldn't it?

**Comment by liebsc21** [comment]
Thanks for the reply!
I also want to connect the custom button to a callback function. `v.Btn` does not seem to have an on_click attribute or similar, does it?
With `Button` it works fine:
```
from typing import Callable

import solara

label = solara.reactive("$n_\mathrm{clicks} = $")
number = solara.reactive(0)

@solara.component
def MarkdownButton(on_click: Callable, label: str = ""):
    return solara.Button(label=solara.Markdown(label), on_click=on_click)

def update_label():
    number.value += 1

@solara.component
def Page():
    return MarkdownButton(label=label.value + str(number.value), on_click=update_label)
```

Within the definition of the custom button: What's the difference of your syntax using the context manager and mine that soley uses the return keyword?

About #175: The example works for me using solara 1.25.0.

**Comment by maartenbreddels** [comment]
You can check the code https://github.com/widgetti/solara/blob/master/solara/components/button.py to see how on_click is implemented (using use_event).
I hope that helps. But you will also see that solara.Button is nearly the same as v.Btn :)
