### ISSUE TITLE
bqplot: incorrect labeling on axes

### ISSUE THREAD

**Issue by albop** [widgetti/solara#470]
I believe the online example : https://solara.dev/examples/libraries/bqplot does not do exactly what it should.
In the code, there is: 

```
def Page(x=x0, ymax=5):
   ....

    x_scale = bqplot.LinearScale()
    if log_scale.value:
        y_scale = bqplot.LogScale(min=0.1, max=ymax)
    else:
        y_scale = bqplot.LinearScale(min=0, max=ymax)
```

so, by default, the labels on the x and y axis should be up to 5.
But on the website, you can see it is always between 0 and 1.
I replicate the same behaviour on my laptop.

![Screenshot from 2024-01-18 18-25-02](https://github.com/widgetti/solara/assets/276777/ea2ddcb1-7432-4174-b18e-0912f03603b3)

**Comment by maartenbreddels** [comment]
I think there was a broken bqplot release, and it appears to be fixed now. Would be great if you can confirm that as well. I'm closing this as fixed, please re-open if needed.

**Comment by albop** [comment]
Hmm, on my computer, it is still broken. I have bqplot = "0.12.43.*" and solara = "1.28.0.*", apparently the newest version, all from conda-forge. 
Is it supposed to be fixed in the released version  or just in master ?
