### ISSUE TITLE
json datetime encode support

### ISSUE THREAD

**Issue by zhuoqiang** [widgetti/solara#475]
when I use plotly in solara, if axis contains `datetime`, the chart shows blank without data, and solara server complains:

```shell
ERROR:    Error sending message: datetime.date(2023, 11, 21) is not JSON serializable
Traceback (most recent call last):
  File "python3.12/site-packages/solara/server/kernel.py", line 249, in send
    wire_message = json_dumps(msg)
                   ^^^^^^^^^^^^^^^
  File "python3.12/site-packages/solara/server/kernel.py", line 68, in json_dumps
    return jsonmodule.dumps(
           ^^^^^^^^^^^^^^^^^
  File "python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "python3.12/site-packages/solara/server/kernel.py", line 60, in json_default
    raise TypeError("%r is not JSON serializable" % obj)
TypeError: datetime.date(2023, 11, 21) is not JSON serializable
```

turns out the plotly chart object contains `datetime` which could not be handle by python standard json lib by default. and I could not find a way to provide my own `JSONEncoder` for solara to use.

**Comment by maartenbreddels** [comment]
Do you have the code to reproduce this (something I can copy paste), because looking at https://github.com/jupyter/jupyter_client/blob/main/jupyter_client/jsonutil.py it seems that only datetime is supported in jupyter as well, not date.

**Comment by zhuoqiang** [comment]
> Do you have the code to reproduce this (something I can copy paste), because looking at https://github.com/jupyter/jupyter_client/blob/main/jupyter_client/jsonutil.py it seems that only datetime is supported in jupyter as well, not date.

It turns out the root cause of this issue is that: the dtype of the date time column in the dataframe is **object** instead of a normal datetime type like **datetime64[ns]**. 

Once I convert the dtype to datetme64[ns] it works perfectly.

**Comment by maartenbreddels** [comment]
Ok, so this probably also didn't work in Jupyter notebook/lab. I'm assuming this to be a user-error or an issue with plotly (for not doing the conversion). Thank you for the update.
