### ISSUE TITLE
assign global value from local scope based on condition

### ISSUE THREAD

**Issue by mattijn** [widgetti/solara#491]
Thanks for the work in this library!
I've the following issue that I cannot understand. 
I try to update a `reactive` variable based on an `on_click` event in a button.

But the behaviour I see, is that this global reactive variable is updated even when the `on_click` event is not called:

![DpLPRmKB9T](https://github.com/widgetti/solara/assets/5186265/5a4c4a7b-60ce-4996-bc53-f68d31dcbd7a)

Used python specification:

```python
import solara

global_slider_value = solara.reactive(0)

@solara.component
def InputFields():
    local_slider_value, set_local_slider_value = solara.use_state(5)
    
    def my_click_handler():
        global_slider_value.value = local_slider_value        
        
    solara.SliderInt(
        label="Slider value", 
        value=local_slider_value, 
        min=2, max=10, 
        on_value=set_local_slider_value, 
        tick_labels=True
    )
    solara.Info(
        label=f"Local slider value (updates when slider changes): {local_slider_value}"
    )

    solara.Button(
        label="Collect input values", 
        on_click=my_click_handler()
    )


@solara.component
def OutputField():
    solara.Error(f"Global slider value (should only update on Button click): {global_slider_value.value}")

@solara.component
def Page():
    InputFields()
    OutputField()

Page()
```
I hope I merely misunderstand the fundamentals, but it feels a bit odd. Maybe this PR is related: https://github.com/widgetti/solara/pull/455?
Again, thanks for this package!

**Comment by maartenbreddels** [comment]
Hoi Mattijn,

thanks for the kind words.
I've made this mistake myself as well:
> ```python
> on_click=my_click_handler()
> ```

You should pass the function, not call it and assign the return value (which is None). By passing None, we assume you don't want a click handler, so it also is not an error,

Hope this helps.

**Comment by mattijn** [comment]
Great! That is helpful!

![IlybEH9h8b](https://github.com/widgetti/solara/assets/5186265/4699c34b-fa4f-4ecd-a131-6ffab20340e2)

To close this issue as completed, the working python specification:
```python
import solara

global_slider_value = solara.reactive(0)

@solara.component
def InputFields():
    local_slider_value, set_local_slider_value = solara.use_state(5)
    
    def my_click_handler():
        global_slider_value.value = local_slider_value  
        return None
        
    solara.SliderInt(
        label="Slider value", 
        value=local_slider_value, 
        min=2, max=10, 
        on_value=set_local_slider_value, 
        tick_labels=True
    )
    solara.Info(
        label=f"Local slider value (updates when slider changes): {local_slider_value}"
    )

    solara.Button(
        label="Collect input values", 
        on_click=my_click_handler
    )


@solara.component
def OutputField():
    solara.Success(f"Global slider value (updates on Button click): {global_slider_value.value}")

@solara.component
def Page():
    InputFields()
    OutputField()

Page()
```
