### ISSUE TITLE
What's the best way to control a component lifecycle?

### ISSUE THREAD

**Issue by itepifanio** [widgetti/solara#498]
I have more experience developing UI using Vue and when using solara I miss controlling the lifecycle of a component. Sometimes I want to trigger a component callback or some other action once on init/on mounted for example and I'm not completely sure how to do this using solara components. 

For this cases the best approach is to use a [vue component](https://solara.dev/examples/general/vue_component) or there are some workarounds?

**Comment by maartenbreddels** [comment]
Hi,

I'm not exactly sure what you mean. If you are ok with a 'mount at the python side', you may want to look into https://solara.dev/api/use_effect
Let me know if that helps you, otherwise, maybe you want to elaborate more on what you are trying to do.

Regards,

Maarten

**Comment by itepifanio** [comment]
@maartenbreddels yes, that exactly what I was looking for
