### ISSUE TITLE
app layout api page refers to (broken) scatter example

### ISSUE THREAD

**Issue by Jhsmit** [widgetti/solara#53]
The API page of [AppLayout](https://solara.dev/api/app_layout) refers at the bottom to the 'AppLayout page', but links to 'https://solara.dev/app/scatter', which should be 'https://solara.dev/apps/scatter' (if the intention is to refer to the scatter example)

**Comment by maartenbreddels** [comment]
Thank you! This is no fixed (should be deployed soon)
