### ISSUE TITLE
Question: Highchart JS or Highchart Python implementation

### ISSUE THREAD

**Issue by BFAGIT** [widgetti/solara#530]
Hello Solara community, 
I've discovered the projects a few weeks ago and I can't say how awesome it is. Thanks for all the hard work. 
I wanted to ask if you had any plan on porting the Highchart js library or the Highchart Python? 
I've seen that you have already ported a lot of charting libraries such as Echart, Plotly, matplolib.

Its one of the most used charting library in the javascript world and offers features that no other library do. There is just so many ressources on it and a great community which makes it a very nice library to work with I'm creatin a lot of stock charts on my side and their stock charting library is like no other offering with so many indeicators by default. 

https://www.highcharts.com/demo/stock/stock-tools-gui
https://github.com/highcharts-for-python/highcharts-core/

They have very recently made a wrapper for their charting library to python https://www.highcharts.com/integrations/python/ and it also support jupyterlab natively. 

I'm new so i haven't yet look up to but would you have any guidline on how I could start porting it to solara ? I guess their might be two way directly using the js one like has been done with Echart or which might be simpler is the python/jupyterlab port directly

thanks a lot,
Kind regards
BFAGIT

**Comment by maartenbreddels** [comment]
Hi @BFAGIT,

thank you for the kind works.
If you do not need bi-direction communication (e.g. only push data), you can use similar as in Jupyter, the [display](https://solara.dev/api/display) function. For instance, this works:

```
import solara


from highcharts_core.chart import Chart
from highcharts_core.options.series.area import LineSeries

exponent = solara.reactive(1.2)
series_type = solara.reactive('line')


@solara.component
def Page():
    with solara.Card(f'Demo: exponent={exponent}'):
        solara.Select('Type', value=series_type, values=['line', 'bar'])
        solara.SliderFloat(label='exponent', value=exponent, min=-1, max=2)
        exp = exponent.value
        my_chart = Chart(data = [[1, 1*exp], [2, 2*exp], [3, 3**exp]],
                         series_type = series_type.value)
        display(my_chart)
```

Does this work for you? If you do need bi-directional communication (e.g. events), you can take a look at the ECharts implementation.

Hope this works for you.

Regards,

Maarten

**Comment by maartenbreddels** [comment]
Thanks!

Can I ask you a favour? Could you share the code for your application? I'm looking for a more impressive example than mine, if we make a screencast of that (Feel free to do this yourself if you feel like it) we could use this to advertise this feature.

Cheers,

Maarten

**Comment by BFAGIT** [comment]
Hey @maartenbreddels,
With pleasure. I still need a few more days or week to get to know solara better but I will definetly provide you a Demo for some of the features I've been using for Highchart. I think there is definitly something very cool to do. I'll get back to you here when I have a good demo working.

One thing to note is Highchart python is still under dev, well like most projects ^^, so there are very few small issues here and there but I believe it could be really great with solora and provide some more advanced features.

Best,
BFAGIT
