### ISSUE TITLE
solara docs render poorly with dark system

### ISSUE THREAD

**Issue by havok2063** [widgetti/solara#533]
The Solara docs render with mixed theme when the system theme is set to Dark.  See sidebar versus main content area.  The main content area also renders with low contrast, making it hard to read.   This is in Firefox browser.

<img width="1697" alt="Screenshot 2024-03-01 at 1 19 35 PM" src="https://github.com/widgetti/solara/assets/1836302/eeb12de1-36ab-4b49-9f10-9a217b602e90">

**Comment by iisakkirotko** [comment]
Hi @havok2063!

Indeed, the website does not support full dark theme currently. This will hopefully be implemented sooner rather than later, but some issues with assets still need to be ironed out. You can follow the progress at #513.
