### ISSUE TITLE
Unable to change the width of individual widgets in a Row

### ISSUE THREAD

**Issue by kdheepak** [widgetti/solara#560]
I'm trying to plot a ipydatagrid widget in solara, and it works great when using `solara.Column`:

![image](https://github.com/widgetti/solara/assets/1813121/6a35d39c-e61b-452c-bd71-61f07937e25f)

but if I try to make the tables side by side, i.e. using a `solara.Row`, the individual widgets in this case collapse:

![image](https://github.com/widgetti/solara/assets/1813121/2cd25eea-5589-4513-8358-54d498aa6dd5)

Is there a way to make it equal in width? I tried `justify` as `space-evenly` and no luck. Here's the code to reproduce this:

```python
import solara
import ipydatagrid
import pandas as pd

df = pd.DataFrame({
        "afljasdfljasdfasd": [1,2,3,4],
        "afasjdfkljadsflasdj": [1,2,3,4],
        "fasdlkfjasdljasgsad": [1,2,3,4],
        "gdsalfjsdalkvjasdfas": [1,2,3,4],
        "ajdgakldjalbsdfa": [1,2,3,4],
        "klasdbjasdlbjasl": [1,2,3,4],
        "asdgjlaskdjblaskjbasl": [1,2,3,4],
        "dsfjlasdjfalsdjvlsadk": [1,2,3,4],
        "asdgasjdlfjasdlfkjsadlfjs": [1,2,3,4],
    })

@solara.component
def Page():
    dg = ipydatagrid.DataGrid(df)
    solara.Row(children=[dg, dg])

Page()
```

**Comment by maartenbreddels** [comment]
Hi Dheepak,

Note that we will have some docs on ipydatagrid soon: https://github.com/widgetti/solara/pull/531

But, I think using [solara.Columns](https://solara.dev/api/columns) will in this case be easier, it will make the widths expand (by default).

Hope that helps. solara.Row uses flexbox, and it depends in the flex-grow properties of the children (the datagrids) if they expand or not.

Not a CSS expert thought (is this correct @iisakkirotko ?)

cheers,

Maarten

**Comment by iisakkirotko** [comment]
Hi @kdheepak!

@maartenbreddels is indeed correct. I would go about this by making the top element a `solara.Row`, with two `solara.Column`s as children, with one `dg` each. So:
```python
@solara.component
def Page():
    dg = ipydatagrid.DataGrid(df)
    with solara.Row():
        solara.Column(children=[dg], style={"flex-grow": "1"})
        solara.Column(children=[dg], style={"flex-grow": "1"})
```
Let me know if that works!

**Comment by kdheepak** [comment]
Awesome! That seems to work great! I did try `with solara.Row():` and used two columns in there but using `flex-grow: 1` seems to do the trick!

Thanks for the quick responses!
