### ISSUE TITLE
Out-of-date links on the bottom of Readme

### ISSUE THREAD

**Issue by JovanVeljanoski** [widgetti/solara#577]
These links appear to be broken (Introduction & Quickstart):

<img width="1440" alt="image" src="https://github.com/widgetti/solara/assets/18574951/8fe083e8-4999-4880-a3b1-2917f32970b8">

**Comment by maartenbreddels** [comment]
Thanks Jovan!

**Comment by iisakkirotko** [comment]
Thanks for the issue @JovanVeljanoski! I think this issue due to the fact that the website hasn't been redeployed since fd2aff94a0a882eb9819707fdaa5789613e9e5a4, which changed the route structure of the website. Should be fixed as soon as we redeploy the website!

**Comment by iisakkirotko** [comment]
The links should have already been working for a while, but with c307f2174f62e72363c54bdd591586db535a65e6 they should both point to the right pages.
