### ISSUE TITLE
AppLayout docs are broken

### ISSUE THREAD

**Issue by Ben-Epstein** [widgetti/solara#61]
https://solara.dev/api/app_layout

<img width="947" alt="image" src="https://user-images.githubusercontent.com/22605641/231165072-766bd61c-8cac-4a52-b621-7978a0ff9830.png">

The App Layout link takes you to a broken page. I also cant render the screenshot, and the "Show Code" card just shows me the hyperlink, so I can't recreate the AppLayout locally 
<img width="956" alt="image" src="https://user-images.githubusercontent.com/22605641/231165528-714e6476-b585-4fa9-99f5-a5af34d6a25d.png">

**Comment by maartenbreddels** [comment]
Thanks Ben, this is fixed now. Should be deployed soon
