### ISSUE TITLE
Multipage as package - stripping of prefix not working

### ISSUE THREAD

**Issue by johannesWen** [widgetti/solara#612]
Hi,

I have deployed my solara app as a python package with the following structure:

![grafik](https://github.com/widgetti/solara/assets/57130737/a7efb484-06af-447f-adce-a1e685f51564)

So I want to order the pages by the prefix and then use the rest of the folder name for the URL and Tab names, but unfortunately it is not working properly. 

![grafik](https://github.com/widgetti/solara/assets/57130737/06793641-4471-4fb5-a7bc-2f16f4e69910)

So maybe this is a bug, or I miss something. I have also attached the sample multipage solara app.
Thank you for your help 😃 

[multipage_example.zip](https://github.com/widgetti/solara/files/15036359/multipage_example.zip)

**Comment by maartenbreddels** [comment]
Hi Johannes,

I am starting to think we should advise to start doing multipage like this:
```python
import solara
from . import bar, foo


@solara.component
def Home():
    solara.Markdown("Foo")

routes = [
    solara.Route("/", component=Home, label="Home"),
    solara.Route("bar", component=bar.Page, label="Bar"),
    solara.Route("foo", component=foo.Page, label="Foo"),
]
```


It's very explicit, it's more clear what the order is, and there is less magic going on. What do you think?

cheers,

Maarten

**Comment by johannesWen** [comment]
Hi Maarten,

thank you for the tip with the routes!
Yeah, I like it, to have more control about what is happening 😉 

BR,
Johannes
