### ISSUE TITLE
Issue with pip install of solara version 1.32.1?

### ISSUE THREAD

**Issue by kdheepak** [widgetti/solara#630]
I have the following project:

```
$ poetry run pip list | rg solara
solara                    1.32.1
solara-server             1.32.1
solara-ui                 1.32.1
```

however when I try to import solara, I have issues:

![image](https://github.com/widgetti/solara/assets/1813121/a19e3576-1336-4e77-a25d-0f630abba2fe)

Is there an issue with bundling perhaps?

**Comment by kdheepak** [comment]
Version 1.32.0 appears to be working fine:

![image](https://github.com/widgetti/solara/assets/1813121/5817a94a-e172-4233-963a-f1f502d51c5d)

**Comment by iisakkirotko** [comment]
Hi @kdheepak!

I tried in fresh environments, as well as upgrading from an old version, using both `pip` and `conda`, but everything seemed to work as expected. I didn't try using poetry, so it could be that the issue is isolated to poetry. I'll give that a try soon. Is the project you experienced this with new, or did you upgrade from a previous version of Solara?

**Comment by kdheepak** [comment]
I upgraded from a previous version but also deleted the poetry.lock file and was still able to reproduce this issue, so that was effectively a new project.

**Comment by kdheepak** [comment]
This was happening on Windows btw

**Comment by mariobuikhuizen** [comment]
I tried it on windows, and couldn't reproduce the issue. This worked for me:
```shell
micromamba create -n poetry-solara -c conda-forge python=3.11 pip poetry
micromamba activate poetry-solara
poetry new poetry-solara
cd .\poetry-solara\
poetry add solara
notepad app.py
solara run app.py
```

**Comment by maartenbreddels** [comment]
From your screenshot, Python thinks solara is a namespace package (probably an empty directory left over for unknown reasons?). You can take a look at `solara.__path__` to debug this yourself, possibly remove this directory by hand.
