### ISSUE TITLE
Documentation getting started introduction links lead to 404 not found

### ISSUE THREAD

**Issue by HugoP** [widgetti/solara#633]
Hi,

Take note I just started looking at solara today. So total noob.

I was going thru the [Introduction](https://github.com/widgetti/solara/blob/master/solara/website/pages/documentation/getting_started/content/01-introduction.md) and found most of the link's are not working.

Is this the best place to start?

Kind regards

**Comment by iisakkirotko** [comment]
Hey @HugoP!

The links are all relative - they're intended for the website, on which `01-introduction.md` is directly included, see [`documentation/getting_started/introduction`](https://solara.dev/documentation/getting_started/introduction) on the website. So if you want the links to work you should view the documentation on [solara.dev](https://solara.dev)

**Comment by HugoP** [comment]
Hi @iisakkirotko!

Thanks for the prompt reply.

Since then I got my own local dev server running after cloning the github repo and.

```
solara run solara.website.pages
```

Not 100% sure it's the correct way but looking good so far.

**Comment by iisakkirotko** [comment]
That's indeed the correct way to run the documentation locally. It should be identical to what's on our website, at https://solara.dev/documentation
