### ISSUE TITLE
Feature Request: Programmatically focus on a component

### ISSUE THREAD

**Issue by JovanVeljanoski** [widgetti/solara#640]
It would be nice to make available the functionality to focus on a component (say a text input component) after interacting with another component (i.e. a button). 

An example of this would be something like:
 - user enters some text in an input text field
 - user presses some button
 - the same (or another) text field is automatically in focus -> no need to use the mouse to select that component in order to enter text.

I saw that this is possible via the `.focus()`  method in `ipyvuetify`, but that is not exposed in solara. There is a kwarg that makes a certain input text field be in focus when the app starts, but that is lost once the user interacts with other components (buttons, sliders etc..).

**Comment by maartenbreddels** [comment]
Hi Jovan,

good question, I'd like to see this in action before I can answer this fully, lets call next week and you can demo this to us ok?

I think there is one argument we can expose, which is the `autofocus` property, that is available in inputs in vuetify ([it's an HTML feature](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus)). But I'd like @mariobuikhuizen 's input on this since he wasn't a big fan of programmatically focus, so I wonder what he thinks of this.


This seemed to work nicely:

```python
import solara

show_dialog = solara.reactive(False)

@solara.component
def Page():
    solara.InputText("No focus")
    solara.InputText("Focus", autofocus=True)
    solara.InputText("No focus")
    solara.Button("Show dialog", on_click=lambda: show_dialog.set(True))

    with solara.v.Dialog(v_model=show_dialog.value, on_v_model=show_dialog.set, persistent=True, max_width="500px"):
        with solara.v.Sheet(class_="pa-4"):
            solara.InputText("No focus")
            solara.InputText("Focus", autofocus=True)
            solara.InputText("No focus")
            solara.Button("Close", on_click=lambda: show_dialog.set(False))
```

But it would require this patch:
```diff
diff --git a/solara/components/input.py b/solara/components/input.py
index 0332d709..31b7fc79 100644
--- a/solara/components/input.py
+++ b/solara/components/input.py
@@ -47,6 +47,7 @@ def InputText(
     update_events: List[str] = ["blur", "keyup.enter"],
     error: Union[bool, str] = False,
     message: Optional[str] = None,
+    autofocus: bool = False,
     classes: List[str] = [],
     style: Optional[Union[str, Dict[str, str]]] = None,
 ):
@@ -131,6 +132,7 @@ def InputText(
         type="password" if password else None,
         error=bool(error),
         messages=messages,
+        autofocus=autofocus,
         class_=classes_flat,
         style_=style_flat,
     )
```

Regards,

Maarten

**Comment by JovanVeljanoski** [comment]
Hi! 

Thanks for the help! I don't think this works for my case tho (i tried it before). What this thing does (i think) it focuses the element in question on the page load, but after that it does not re-focus.. 

I think that's why `ipyvuetify` component has the `.focus()` method, that works (but without the reactivity of course)

**Comment by maartenbreddels** [comment]
Been thinking on this for a while, and I think a button click can be done:
https://py.cafe/maartenbreddels/solara-autofocus

But changing a slider might be difficult. 

A more aggressive one is this:
https://py.cafe/maartenbreddels/solara-force-focus

To control focus on a different fields, you need to have several of these and orchestrate (using enabled) it via a reactive variable I think

I hope that helps.

**Comment by JovanVeljanoski** [comment]
Hi, 

thanks for the ideas. Unfortunately neither work completely for my usecase. Maybe I can outline what happens..
The relevant (TextField) component is focused on app start. But as the flow of the app continues, the parent component is re-rendered and then the relevant TextField component is out of focus.

Some skeleton code

```python

with solara.Div():

        with solara.Card(style={'width': '50%'}):
            solara.SelectMultiple(...)

        if some_variable_is_true
            StartSessionComponent...)
        else:
            ComponentWithTextInput(param1, param2, param3)
```

Then elsewhere (another file)
```python
@solara.component
def ComponentWithTextInput(param1, param2, param3):
    my_input = solara.use_reactive(param1)
    with solara.Card(style={'width': '50%'}):

        solara.Markdown(text
        with ForceFocus(enabled=True, target_query='input', refocus_delay=0.1):
            solara.v.TextField(label='my input', v_model=my_input.value, on_v_model=my_input.set)
    if some_condition:
            with solara.HBox():
                solara.Button('Do stuff', on_click=lambda: check_func(user_input.value)
```

Maybe this is some edge case and it requires work outside of python..

**Comment by maartenbreddels** [comment]
Could you create a (non-working) example on PyCafe to demonstrate that exact issue? (you can fork my project and add the stuff that shows how it does not work)

**Comment by JovanVeljanoski** [comment]
Hi, 

It is a bit tricky, but i think i made an example that reproduces the issue: Here is the link
https://py.cafe/b7yuvghp7/telling-carrot 

After some debugging I think the problem is something related to hot-keys: [I am using your code from here](https://github.com/widgetti/solara/issues/641#issuecomment-2104622270).

If I do not use hotkeys, i everything works expected (with the force focus vue code). But if I do use hot-keys, the autofocus function is lost at some point (after the 2nd press or so). 

I hope this helps.

**Comment by maartenbreddels** [comment]
I tried reproducing it, but it behaves ok for me. It keeps focus on the input for both chrome and firefix.

**Comment by JovanVeljanoski** [comment]
I managed to make this work. If anyone is interested this is what I ended up doing. I modified the examples above from @maartenbreddels and created a vue file 

```js
<template>
    <jupyter-widget :widget="children[0]"></jupyter-widget>
</template>

<script>
module.exports = {
    props: ['enabled', 'target_query', 'refocus_trigger'],
    watch: {
        refocus_trigger() {
            if (this.enabled) {
                this.$nextTick(this.refocus);
            }
        },
        enabled(newValue) {
            if (newValue) {
                this.$nextTick(this.refocus);
            }
        }
    },
    mounted() {
        if (this.enabled) {
            this.$nextTick(this.refocus);
        }
    },
    methods: {
        refocus() {
            const el = this.$el.querySelector(this.target_query)
            if (el && document.activeElement !== el) {
                el.focus()
            }
        }
    }
}
</script>

<style id="forcefocus"></style>
```

That will focus on the component when the trigger is changed. So in the python code, i have a component like

```python
@solara.component_vue('force_focus_on_trigger.vue')
def FocusOnTrigger(enabled=True, children=[], target_query='input', refocus_trigger=0):
    '''Force focus on a target element when enabled is True.

    Notes:
    - `param: children`: only one element is allowed
    - `param: target_query`: query selector for the target element
    - `param: refocus_trigger`: trigger to refocus on the target element. This needs to change in order to refocus on the target element.
    '''
    ...
```

Then in my actual component I do something like this, where after whatever even i need (usually a hotkey press or a button press), i can programmatically focus on that component. 

```python
focus_trigger = solara.use_reactive(0)

with FocusOnTrigger(enabled=session_state.is_session_active, target_query='input', refocus_trigger=refocus_trigger.value):
            solara.v.TextField(
                label='Your translation',
                v_model=user_input.value,
                on_v_model=user_input.set,
                disabled=not session_state.is_session_active or question.is_checked,
                continuous_update=True,
                autofocus=True,   # This is so that the component is initialized with focus on it
            )

#
solara.Button('Next', on_click=lambda: (callback(), refocus_trigger.set(refocus_trigger.value + 1)))
            if hotkey_active:
                HotKey(key='Enter', event_pressed=lambda ignore: (callback(), refocus_trigger.set(refocus_trigger.value + 1)))
```

With this solution, the component is now always in focus (not a hard force) but you can choose when you want it to be in focus, programmatically.
