### ISSUE TITLE
[Bug] Solara `FigurePlotly` seems to be broken

### ISSUE THREAD

**Issue by Ben-Epstein** [widgetti/solara#66]
This code used to work, but now it hangs forever

## Version info
solara 1.10.0
plotly 5.9.0

code
```
import pandas as pd
import solara as sl
import plotly.express as px

@sl.component
def Page():
    df = pd.read_csv("conv_intent.csv")
    df["text_length"] = df.text.str.len()
    df["id"] = list(range(len(df)))
    df["hovertext"] = df.text.str.wrap(30).str.replace("\n", "<br>")
    fig = px.scatter(
        df,
        x="x",
        y="y",
        custom_data=[df["id"]],
        hover_data=["hovertext"],
    )
    fig.update_layout(showlegend=False)
    fig.update_xaxes(visible=False)
    fig.update_yaxes(visible=False)
    fig.update_traces(marker_size=2)
    
    sl.FigurePlotly(fig)
    
Page()
```
The code outside of a component (plotly only) works

I've attached the file below
[conv_intent.csv](https://github.com/widgetti/solara/files/11213466/conv_intent.csv)

**Comment by Ben-Epstein** [comment]
Upgrading to the latest plotly `5.14.1` causes the cell to complete, but no output plot is created

**Comment by iisakkirotko** [comment]
Seems to work fine now on both [PyCafe](https://py.cafe/iisakkirotko/solara-issue-66) and jupyter notebook & lab. Feel free to re-open if this still affects some platforms!
