### ISSUE TITLE
ipywidget Accordion not working properly

### ISSUE THREAD

**Issue by lopezvoliver** [widgetti/solara#677]
Here's a simple example of a label within an [Accordion widget](https://ipywidgets.readthedocs.io/en/8.1.3/examples/Widget%20List.html#accordion) working in an `ipyleaflet` Map in a Jupyter notebook:

```python
import ipyleaflet
import ipywidgets as widgets

label = widgets.Label("General Kenobi!")
accordion = widgets.Accordion(children=[label], titles=['Hello there!'])

m = ipyleaflet.Map()
toolbar = ipyleaflet.WidgetControl(widget=accordion, 
    position="topright",
)  
m.add(toolbar)
m
```

![image](https://github.com/widgetti/solara/assets/14804652/6f644f36-f7c7-41e2-92f3-9dd330b371c9)

Closed accordion

![image](https://github.com/widgetti/solara/assets/14804652/018193d0-cfbc-4f45-a538-bd4d4a69800b)

Open 

Here's the corresponding code for Solara:

```python
import solara
import ipyleaflet
import ipywidgets as widgets

zoom = solara.reactive(6)
center = solara.reactive((0,0))

class Map(ipyleaflet.Map):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        label = widgets.Label("General Kenobi!")
        accordion = widgets.Accordion(children=[label], titles=['Hello there!'])
        toolbar = ipyleaflet.WidgetControl(widget=accordion, 
            position="topright",
        )  
        self.add(toolbar)


@solara.component
def Page():
    with solara.Column() as main:
        map = Map.element(  # type: ignore
            zoom=zoom.value,
            on_zoom = zoom.set,
            center=center.value,
            on_center=center.set,
            scroll_wheel_zoom=True,
            toolbar_ctrl=False,
            data_ctrl=False,
        )
        return main
```

Unfortunately, the accordion widget does not close:

![solara_bug_accordion](https://github.com/widgetti/solara/assets/14804652/0c52f358-5264-46d9-ba82-5bd2d9269cae)

Heres my information on Solara, ipyleaflet, and ipywidgets versions:

Solara version: 1.33.0
ipyleaflet version: 0.19.1
ipywidgets version: 8.1.3

**Comment by iisakkirotko** [comment]
Hi @lopezvoliver! Thanks for the issue. It seems like the behaviour of `ipywidgets.Accordion` is in general broken when running in Solara server. I'll try to get this fixed in the coming few days.
