### ISSUE TITLE
Input field states do not update correctly when that input is inside a "with tooltip:"

### ISSUE THREAD

**Issue by daoslies** [widgetti/solara#683]
The following input field does not update state correctly. Only doing so if the user presses enter. (should also update on exit)
 
exact_text_match, set_exact_text_match = solara.use_state("")

 with solara.Tooltip("Exact text matching (case insensitive)"):
                solara.InputText("Text", value=exact_text_match, on_value=set_exact_text_match)

--

Without the tooltip the state updates as anticipated:

solara.InputText("Text", value=exact_text_match, on_value=set_exact_text_match)

--

With continuous update the state updates as anticipated:   
               
 with solara.Tooltip("Exact text matching (case insensitive)"):
                solara.InputText("Text", value=exact_text_match, on_value=set_exact_text_match, continuous_update=True)
                
--
                
So there is a reasonable work around with continuous update, but having a tooltip shouldn't then require a continuous update.

**Comment by iisakkirotko** [comment]
Hi @daoslies!

Thanks for reporting this bug, and sorry for taking a while to get back to you. `continuous_update` should indeed not be required to make this work. I'll do some more digging and get back to you once I locate the source of the issue.
