### ISSUE TITLE
Typo in type hint of `solara.components.tooltip.Tooltip`

### ISSUE THREAD

**Issue by MG-MW** [widgetti/solara#685]
There is a typo in the definition of the `Tooltip` component:
 https://github.com/widgetti/solara/blob/714e41d8950b38bd14435ae4356d9d841c4a278f/solara/components/tooltip.py#L10C5-L10C40
Currently, it's like this:

```python
@solara.component
def Tooltip(
    tooltip=Union[str, solara.Element],
    children=[],
    color: Optional[str] = None,
):
```

but should be

```python
@solara.component
def Tooltip(
    tooltip: Union[str, solara.Element],
    children=[],
    color: Optional[str] = None,
):
```

**Comment by iisakkirotko** [comment]
Hey @MG-MW! First off, sorry for taking a while to get back to you, we've been quite busy the last couple of weeks, working on a different project. Regardless, thanks a lot for pointing out this issue, that is indeed clearly incorrect. Do you want to open a PR to rectify it?
