### ISSUE TITLE
Clarification on `solara-enterprise` 🤝 FOSS

### ISSUE THREAD

**Issue by ntjess** [widgetti/solara#697]
It is very helpful to have out-of-box instructions for auth with solara apps -- thank you! However, I am curious about the long-term availability of this module. Typically, "enterprise" namespaces are reserved for / associated with paid framework features. Is your intent to provide `solara-enterprise` as a free, open source downloadable module indefinitely? Or will it become part of a "solara enterprise" paid ecosystem in the future?

(Edit: I'm just now realizing there is also a discussion board; forgive me if this should've been posted as a question there instead)

**Comment by maartenbreddels** [comment]
Hi Nathan,

No, solara-enterprise is not Open Source (with capital letters). This is visible from the license:
 * https://pypi.org/project/solara-enterprise/
 * https://github.com/widgetti/solara/blob/master/packages/solara-enterprise/LICENSE
 * https://github.com/widgetti/solara/blob/a2ca2164e81b7aa0bc742e45c750e1d3f2e3c83d/packages/solara-enterprise/pyproject.toml#L11

And when using an enterprise feature, this is warned about in the console:
```
Using the enterprise auth feature requires a license, unless used for non-commerical use. Please contact us at contact@solara.dev to get a license.
```

However, solara-enterprise will stay free for non-commercial use.
Also, features that are in solara will **not be moved to solara-enterprise**.

For further clarification, we also added explicit wording at:
 https://solara.dev/documentation/advanced/enterprise

Do you think this is good enough? Or should we add information/warnings in more places?


Regards,

Maarten

PS: I'm ok with either issues or discussions.

**Comment by ntjess** [comment]
This is great, thank you. I neglected to check the package license which is why I missed it the first time -- adding that phrase to the documentation is sufficient.
