### ISSUE TITLE
Regular non-Solara plots not showing in Jupyter Notebooks after Solara has been used

### ISSUE THREAD

**Issue by EwoutH** [widgetti/solara#703]
For some reason, regular matplotlib and seaborn plots don't show anymore *after* a Solara page has been initiated. In the code below you can see the first seaborn plot showing well, but the second not showing.

In PyCharm, the first plot is also shown fine, but instead of just not showing the second plot anymore, but gives an error:

```
ipykernel_29332\2165788151.py:2: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
```

Here's a notebook to reproduce: [solara_bug_plotting.zip](https://github.com/user-attachments/files/16086917/solara_bug_plotting.zip)
And here's the same notebook [in Google Colab](https://colab.research.google.com/drive/1R7taevvvmrxx7Bc7y0BcLT0XpgVaZvyT?usp=sharing).

First plot shows fine:
![image](https://github.com/widgetti/solara/assets/15776622/58e45b89-b971-4baa-8f49-2b4456acf3a7)

After a Solara component, the second errors or doesn't show anymore:

![image](https://github.com/widgetti/solara/assets/15776622/d89b6950-aa10-4c4d-9bd0-d4836ab24b63)

**Comment by EwoutH** [comment]
A workaround is adding `%matplotlib inline` before the second plot.

I still think this is weird behavior.

**Comment by maartenbreddels** [comment]
Does this also happen after a simple solara import?
After this happens, can you check if `solara.server.patch` is in sys.modules?

**Comment by EwoutH** [comment]
Thanks for getting back.

Taking some minimal examples, it looks like everything works fine: [solara_minimal_test.zip](https://github.com/user-attachments/files/16087416/solara_minimal_test.zip)

Which means probably something is wrong with our implementation. Can you spot anything obvious?
- Implementation: https://github.com/projectmesa/mesa/blob/74e2df6fdfc2d5172f84eb96469b277b35bfd795/mesa/visualization/jupyter_viz.py#L92
- Usage tutorial: https://mesa.readthedocs.io/en/latest/tutorials/visualization_tutorial.html

**Comment by maartenbreddels** [comment]
https://github.com/projectmesa/mesa/blob/74e2df6fdfc2d5172f84eb96469b277b35bfd795/mesa/visualization/jupyter_viz.py#L39 seems suspicious.
Maybe you have added that because that was needed before https://github.com/widgetti/solara/pull/540 to run under solara server.
Now things should just run.

**Comment by EwoutH** [comment]
I think that help, I at least don't need the `%matplotlib inline` anymore (which is quite logical in hindsight).

The JetBrains (PyCharm) implementation is also still not rock solid:
![image](https://github.com/widgetti/solara/assets/15776622/7ea0f0b5-f8ab-4c1c-a280-9b982435a494)

But it now works most of the time, with reloading a cell or two!

Thanks for the quick responses, really appreciated!
