### ISSUE TITLE
Documentation request: elaborate on proper use of `Reactive.subscribe()`

### ISSUE THREAD

**Issue by ntjess** [widgetti/solara#704]
Use case: I want to add a listener to a reactive variable's changes, but unlike `use_effect`, I do _not_ want the listener to fire on the initial value -- only on changes.

I can do this:
```python
_unused = solara.use_reactive(variable, on_change=listener)
```
but I was wondering if I can simply leverage `subscribe()` directly. The mechanics around `forward_on_change` and `update` are confusing to me, so it would be helpful to understand how to leverage subscription hooks.

**Comment by maartenbreddels** [comment]
Sorry for the late reply, does this do what you want:
```python

import solara

clicks = solara.reactive(0)


@solara.component
def Page():
    print("The component render function gets called")
    def link():
        def change_handler(new_value):
            print("new value", new_value)
        print("subscribed")
        # subscribe returns an unsubscribe, which the cleanup of use_effect will call
        return clicks.subscribe(change_handler)

    solara.use_effect(link, [])
    def increment():
        clicks.value += 1
        print("clicks", clicks)  # noqa

    solara.Button(label=f"Clicked: {clicks}", on_click=increment)

```
[Run and edit this code snippet at PyCafe](https://py.cafe/snippet/solara/v1#c=H4sIALo0kWYAA3VWbU_jOBD-K1H2C6ujUZOWUpAinW5130-n033ZrpCTOI2pYwfboXQR__2eGaehsDqQEJ4Zz8szM4_zmta2kel9ujOqH6wLibdaOLEzO1NrVR98Uk6izElRB_Usr5ZfSb0zv0-K2uKqkSbsTCPb5C-xl1df73cmwc_glAlXu_SfTiazXeIkLF3SjgYerUn2MvikFlrLZpfCO90kV1qZw-zqLKw7YfbyAX8bLd2VkceHZ6FHeWl3GRoGCRvs0uvk3frd-Gzox8rXTlUXSdDPl2RWIPEwOuMTYZLRzOLr5NipuksCFamlMOOQ2DYZvXyQbSvrkByV1lzgu9voCvaEcjb7uvpYHkNN5hPW7z6vCJzr5PuPC7yUqZ3sgfAH0KYQXHbyW5nkv5YeTQig-N9XKtvYJx6Ei_B_jCFYc6VFJXXZ7tJvZC2b--Q13nsjF9Y88Kmc00GK6XXq5NOoosBj5M6TBk04DTSEUYKzGIZ_lTym963QXl6nslHhTyMqDavgRkiGU-iswZ3hZBvVyMXzMitushyXtTjZMaT3r6mzNvxt4eb1HMHhdJ3WndINZjC9_z5rgqi8DP-vhGYQocMByWXDKX37gd-367RVWqKc7z8Q2dYHOn6zJqBI2H5JOuG7-6RZbrZLWdzl1brIW1FtqiZfbfPler0ttje37c4Ic1K2LNfZOlvi5PbWFIu6bVVZFqss_yRcVMo0yuw9tHlWZEu0q0d0MkKNZZlnK77i0a-DNGQHz-i8CMHRafJZifpAc1mWwI8FUoxBtaP2dhzWlFBeZAXkmOu6K8tNtiSzGgcZrNXwdYNY8FxLh4uU7xLeb7MCt2IBeZajNTh1wgHkhbGuF1r9lK4sV7hMhjww5RZZ3eJk-z5mBFUjq3E_nMgN1HOhjaytE8HCB5yTe2wA1qN56bmaWxLJF1mjHLOn-pckaQHJo7fGI_9ekLjggqhv1D_KCNmuIXlqDAXl1Ls8J6c5d6cbe2GQPqPDt1Vj4GtF19RwOkhnsB_ACiOJCiCiaeXyNuRtEiz20iA7wnBCH4rnEX5RD5cUz4CVy7-b_B9VQ4wZ4VpB5G0zAgtQKaFPd-HrEVvDOd_xSZlHUXB1lBJBMFgsf-wBF3EJCwq7JdePI1KVboH-YKIpIoq6EFuHbG-o2-9C-UwbTqE3ly68dM8UrWDM5j5-VC_wb68M1p7uY7JmA3DOYjjtmT1Ix_N9oZtBoWpyYNcLd2jsEZCsss37caEC_MxFk3gcvGhRBzKjgL0Ig7ZBq2qhDFgWGnikuewBMw8XY9grH0bSkiucTVVr4b2quX8XJZIiwoebHBUSa1AuRJjTDfXVVC2tBSQYuCVLpA8L4U-mJmbIgSbdtEFW1mJON4DnIsYkX_hOTbtDLsY-bk7BMSxCOrAlULpFz-BuwDNjaww_UIR0mvYBe4qQSywc8Bjky4AHh4YCozRHHLCxoD7sNAN0m92QTGumH1TJ7rUIVFajyPs6LvTgbC_xVo5-HiukG-2hGsKCiOWgICdk1wB-8LQnBM1dtn3PAPTsbC09D0SsZ3QSAygmQqNop5rKiZNXUHHzEKHfvI7DqefJkC-gbY8tIiSoeNbF96ULYYg-Weg8mn9u6R2jFFe6EUHGXAs44Pgsp-VaaLvfx0SQLqlOgsiKOJW9_uyfoATHXMDMn1202ER_iEOvKAaD01_xoru2Xq1WdwtUrRCeGJEmFP0mzd1281mDWA7fK3BJPD2dqBdEf-cwQ-N5T3Bhe5GOx6dbERxetdkUlD4O01uwIUpC1V698BbwzHqj8A7wDPNLEd95PvK4xfNMEJ_EI78gZxF2VYFg5vfMB7xghDr8TYQDkdMyBB7LFfPqxCoNDzXqwUW8Cqfae1Di9FYCnmjBq4ISVYAXft9A-_BLHwOEyS99xlZgfov1cpWDaGCGB-fDMK0jzKNT4LeeloI5nsOCUcA0q8g-dH5WYFX0G7nzWBxFqLvG4gn7OBgs568PnstLwjnWYMOADvG8IvWjBOFoyy__OhIJRBIP7fQVQVxLsWTl4QFv9HkzqcfROipoNRjSiW_xwXAuNCZI1Os9PnT9k1ZBInj69h_eyLq0ZwwAAA)




I am unsure actually about if we should continue to support subscribe, and I'm not keen on going the signals route (having a @solara.reactive_effect decorator that gets executed (async) after a reactive variable has changed.
That avoids issues with diamond dependencies.

I'm curious, what kinda of use case is this? And in your code, the listener does not get called directly does it?

**Comment by ntjess** [comment]
Thanks for the explanation!

I was looking for a combination of `@task` and `use_task`. That is, a non-blocking task that runs on demand, scoped to a component. `task` is globally shared, and `use_task` executes on initialization. So I ended up using the following pattern:

```python
def use_task_on_change(func, counter: Reactive[int]):
    def wrapper():
        if counter.value < 1:
            return None
        return func()

    return use_task(wrapper, dependencies=[counter.value])
```

It requires an intermediate state that prevents the initial run from having an effect. Is there a more appropriate pattern?

**Comment by maartenbreddels** [comment]
> `use_task` executes on initialization

If you pass dependencies=None, it will not auto execute (I wanted this to be the default, and will probably change that in the future). I've clarified this in 71cdcce78e87ddb4aa9b493d4843fe3b232dfd5c

Together with the above code:
```python
import asyncio
import solara
import solara.lab

clicks = solara.reactive(0)


async def run():
    await asyncio.sleep(1)
    return 42


def use_call_on_change(f, reactive_var):
    def link():
        def change_handler(new_value):
            print("new value", new_value)
            f()
        print("subscribed")
        return reactive_var.subscribe(change_handler)
    solara.use_effect(link, [reactive_var])

@solara.component
def Page():
    task = solara.lab.use_task(run, dependencies=None)
    use_call_on_change(task, clicks)

    def increment():
        clicks.value += 1
        print("clicks", clicks)  # noqa

    solara.Button(label=f"Clicked: {clicks}", on_click=increment)
    if task.finished:
        solara.Success(f"Result of task == {task.value}")
    if task.not_called:
        solara.Info("never called")
    solara.ProgressLinear(task.pending)
```
[Run and edit this code snippet at PyCafe](https://py.cafe/snippet/solara/v1#c=H4sIAL9nkWYAA3VW3WrbSBR-FaHeuKwtLNlxnIBg2bIXC8tSurA3dQkjaWRNLM0oM6M4bsi773fOyIqTtgmEzPk_3_nTc1yaSsa3sep6Y30k3EmXyuz0-HamFVa8eyatKHZ6p8tWlQcX5WeylaL06lHOlh-JvdNsLapkHdlBzz7e7nSEH3EUavKUuFbKfpZCg3hW-sHqaJ0FA6Q6OHlXira9M_qubITey1k9h2Dwdfco7NkwSbdKHyZPZ2JQu8PfqpV2puURau0gL-Xop7dK-9kuhkDEArt4Hr1KvxWuZxeEs6YbCldaVchqF1-wx7Qug04m0dnb8Ea1EVPKXta1LP2MUptHXy-NfGOgfx9lS4Mqaal9AO6zAFTnFL1wh9dKoYBsmagz1GYOmHoJLZREuvwfWBnD-An6pDSPQvHZ_xlmpUsrO_h_U4AgmDCE0W95lP6IWhAhsEerUfQh0uYBjfcGjD8G742eIXrZ5vUu_kTSsrqNnoPeC5mgQOmVT-GMqaiaUUhqpZVroPYayGj_36EspXMzmP4i3dD6yASdKM-jZ1bmNODnnU1tPMP0M6t_6dpwUz1KGwWhSX8U-WzN3sLz30pLYRnhhOqh9P5jPI-tfBhUyMVhVs9DCY4_9TS9gYK36Pv_lDzGt7VonZzHslL-Ty2KFlLeDqD0J98YDZ3-ZCpVycXjMsmukhTKrTiZwce3z7E1xn8xMPN89mDxmsdlo9rKSqh_nTheFE76XzPB6YVv8EBwSX-KX77h92Ue16qVSOfrN3g25YGen4z2SBKyH6JGuOY2qpab7VJmN2mxztJaFJuiSlfbdLleb7Pt1XWNJaNPyuT5OlknS7zs3uhsUda1yvNslaTviItCMawO3DTJkiU6rYN3EkKOeZ4mK1ZxaLWD1CQHy2ha4b2l12izEOWBipnnwI8JUgxe1UPrzNCvKaA0S7DHgL0omzzfJEsSK_GQ3pgWtq7gC5ZLaaFI8S5h_TrJoBUSSJMUpcGrERYgL7SxnWjVd2nzfAVlEuRez7eI6hov03UhIrAqWQz7_kRmwJ4SrWRprPAGNmCczGN4MefVU8fZXBNJPskS6eg95b8kSg1I7p3RDvF3gsgZJ0R1o_pRRIh2DcpDpckph96kKRlNuTrN0AmN8Bkd1laVhq0Vqan-dJBWY7SBFVoSGYBE3crpbcjaSFjspUZ0hOGIPhiPA-wiH04pvAErp38z2j-qai89tAiuFUjOVAOwUOQD6UAXtu4xNRzzDb-UvhcZZ0chEQS9wd4KNeAkLmFBYtdk-n5AqNIuUB90NHlEUhdkYxHtFVX7lYgNgQkn15tLE05arA5CnDCb6viWvcC_ndIYe9JHZ00CWJeL_rTn7UE87u8L3gQKZZMCu07YQ2WOgGSVbF6fC-VhZ0qayEPvRI08EBk57ITvW-NbVSyUxrkCBxapLzvAzM3FGHbK-YG4ZApvXZStcE6VXL-LFIkR4IMmewXFaKQLEvp0Q3XVRU1jAQoabskU6fxi_MAgkxg9EI2XhTHo0w3gufAx0heuUePskImhC5OTsQ8DlxbbEihdo2Yw1-NamxLNDxRBHbu9x5zC5RIDBzx6-dTjclNToJUmjz0mFqsPM80AXSdXRGtbXj_Iks23wlNalSLr6zDQvTWd9I0c3NRWCDfIg9X7BS2WgwKdkF0D-N7RnBA0N8n2NQKsZ2vo1oUAyMBgJRpQjAuNvJ1KSid0XkbJTU2EevM49qeOO0M-YW07TBEhQckzL9yXxvs-2GSidSj-uaQ3jFIY6Up4GWLNYID9M52Ga9Ga_T4EgnCJdRK0rGinstXv3QOY2DEXMPOHEg02rT_4oSuKxuDwVzzoti5Xq9XNAlkruKeNSB2KehPnZrt5z4Evq2iZp7SnxxfVgtbf2U1fOZ4TKGwvwnG455m3uGqTKFb60I-3YEMrCVk79cRTwD3rtMId4B7mSxHuPD-53cJ7WhDvyANfkDMJs6qwYKZ75jwuGKEOe-PCAcm20ntuyxXv1XGrVNzUyAeKuAqn0jmsxPFWAp4gwaOCFJWHFb5vWPuwSx8DhMkPdcZUoH-z9XKVYtFADAfnTTOtA8yDVdhvHQ0F73h2i42CTbMK24fejwpbFfVG7NwWR-HLpjI4YW8bg-n89cF9eblwjiW2oUeFuF8R-lFi4bSGL_86LBKQ8J2M5uavCNq15EsWDhZwo8-TSTUO0oFBo8GQjvsWHwznREOAtHqda_HnoVVewnn88j9lnLbkoA0AAA)

**Comment by ntjess** [comment]
Thanks for the clarification, this makes sense. From a user perspective, in the future it might be nicer to have out-of-the-box support for on-demand tasks.
