### ISSUE TITLE
How to report security issues?

### ISSUE THREAD

**Issue by sunriseXu** [widgetti/solara#708]
Hi, there, Recently I found a security vulnerability in Solara, can you enable [Github bug reporting](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability), so I can report it privately.

**Comment by maartenbreddels** [comment]
Hi,

thank you. I've enabled what I could. Let me know if this is sufficient to report it.

Regards,

Maarten

**Comment by sunriseXu** [comment]
Thank you, I have reported it.

**Comment by maartenbreddels** [comment]
Thanks for this!

Solved by https://github.com/widgetti/solara/security/advisories/GHSA-9794-pc4r-438w
