### ISSUE TITLE
`Card` component's `ma-{margin}` class takes precedence to `classes` 

### ISSUE THREAD

**Issue by edan-bainglass** [widgetti/solara#737]
The view below does not seem to respect my CSS class, at least not my `margin-bottom: ... !important` property. 

I see that `Card` prepends `ma-{margin}` to the class order. On inspection, I see that `ma-0` is applied as `.v-application .ma-0`, which applies a `margin: # !important` property.

Two things:
1. Does `v-application` overrides precedence somehow? There are several `v-application` nested classes throughout. I take it this is `vuetify`? Is their higher precedence by design?
2. The issue really is the `!important` flag on the `ma` class. It effectively blocks any user styles. Can this be modified?

```python
with Card(
    margin=0,
    classes=["container node-card"],
):
    ...
```

**Comment by edan-bainglass** [comment]
My use case:
```python
@component
def QueryPanel(...):
  ...
  Style("query.css")
  with VBox("query-panel"):
    with VBox("node-list"):
      for node in nodes:
        NodeCard(...)

@component
def NodeCard(...):
  ....
  Style("node.css")
  with Card(
    margin=0,
    class=["container node-card"],
  ):
    ...
```
with `node-card` applying a `margin: ... !important`. With the above, my `node-card` class gets outranked by `v-application` classes. However, if I move `node-card` into query.css (nested under `query-panel`), the class outranks `v-application` and all is well. Is this an issue with `Style`, or am I missing something obvious?

**Comment by maartenbreddels** [comment]
Hi Adan,

would you mind making a snippet on https://py.cafe and sharing that here, so it's easy for my to debug a fully working example?

Regards,

Maarten

**Comment by edan-bainglass** [comment]
Done! See [here](https://py.cafe/snippet/solara/v1#c=H4sIAIAjw2YAA71ZeW_bNhT_KpyGAXIhqbHTNJkKD0W7Fit2deuxP-LAkCXK5iaLKkUlcbN8971HijqpJBuKuZhj8p388V3SbpyYJ9QJHbYvuJCk5FkkolW-ylPB9-RTRcWB1LTfcPE2ymmG9FX-XDMHMQd6TnO5yhOakrfRlrqzcJUT0hFxZ47nCPqpYoLugbcEm8YYUOShQC_0DqyjovjI6JUTplFWUs-hCZOv8miTAZcUFewUB7njOcgUB56whPqXR8HiJJiDcBYdeCWd8Ma5pKJkyLUA45zL3zmovDHWBKw8J96xLBEUmM4biow2JZVAvGKJ3Dnh_OTIc_Ys_0Mvj_XqB8q2O7CDS5aAWMoy-gK0llS85LmMWE7FhAVk9TeaF1iKCPU6zu3FrWfxojb07VlwdnR8tjg9PZnPv306P530vlWZw_0GxaGvWZ_cqJ0fzQOlbrF4coYGju9B5X4k6pPdh4IBwH7snfHv9OQhNiUVsB1l9xk1fGgV_9166jYgIoEnj_bIowIfYQMVoA4Cts2RqmLJStQZgihnbGNy5C0skdbQBY1iyXNDr0q6pmlKY-mp36WMJG2Ydfgb3heVBEmPQNB65J08ZNQjH1_w6wE75J-gRqbNxa4Te4iBrDQ8v8DqZ9xp6BgjXerLSKgT4n_PeyoxwbtJHeImJLpSUXoELm6tfpJlez73vDHpIngBfj1xZx5h5RrTcvkeUnp2MTM2USFaipJEaevYUbboVWPk_FFt2W5idtEVbLxzGxUjm6jnJ1bKgc0rJncKfTfOorKk5fJ8pXLLz4B55Vz02fGTckEYIHbt1QDnhObVngqERBtXMkM540lVJMCpAdC_NRphe1ZAcKlMjK2bT8yLA-Ck7EGoFAdXHXmK9Zxd4NV1zE1xt2CiXA_H4Umg5PPL-iQsBCAk2PiyfgcFL1w2yfJAZ03wu1N6UMcSv7wpjl2UJxldx_B3S5edO7xXIuMlXXagsgpYXdeVwuo0g_K1xqK2XDn7hPlFVpUrx6o65hkXwFYIto_EYYIL1MUZi_9amuS062qTBPh8lSgb5SWkykiidyhV6VwspO6qrsNxCT7PelzWfMRSrSq_Hlz8Qg0rw9xsM9zBrlNXfNMnuwVfFcf1Oq1kJeh6bUpklOcc6hoMFmWvzMJVR7U3hlXQIovitsL_D-0C4xe-eVbtYfUmLyr5nl6DAt1HaKa0KZS_fCeBZn7J4kbJO73U1fk9tF-jzN5ZmvQblbleVrVLTJn2clcO_kMpEoOW9giBphg-nAPqXqV-9nrVze2oJZQKM8XrXkZZBa6VUvSDSorDqJThKZQUGFCGzpV0ryXR65gWkvxID6-E4OJOHQbEfiXsQePWAacQ9JRVVa6Uin4G4clSKuOdBmHQ7www9Q0G27qAGuZhW9Xb6rtnpY1gt2PMI-fjbo9zm-DZ0BOV6RC7o8aLeYr81ubLUoBOKviCesqwtpo7SqetfKqIm6iM-DE1lOJl3sHXVNFuJE9r7ZQ4ZLyvnuJnBC9Gjs5-Lh4AsQ56LnwY0a0IKyFdZrpyaUav_S0I-XOrGH60G5OgZ9GGZgCiZtPDE4bNHXiqxAL7yBbgfanpS-UNjF0q5gLN487seDVaVL4EjaK7rlDzd8rD9E1MIWcHqKna0AJ_reAg0RYO342DPfWPEd_JzqlOMdU4RzMONPwty5dHvQO05gYudjutTkV8YBjfzko9dK8cnY1tJhLoIVSVa4vIfuOfDAjtjfXhaitGd7cf6Ejp9vlmouh1-qAzMJCgmevJjVZc8JJhvw-hQWfQ-S_pMyTc4teUaDAYfMa64DkXgkBqXYQ8fkQ2HDj3IfGfFtcI2v6gcQN36ysqyRWFJi1oWcABaUIePdbSRnRRXD8jeiujqQzJydE3tQGtISRHJKok7236mjeOstj1nxyB9cdkMSNf6T4e5dJwA6t6J4JaRtSaouRHxALwYPkWBc_GdAuUemGqvIHvz6qULNX7cHfQigvod_6GyitK83-vNthDHI-sQB2H7PS3UQHHsXg7mhxHAdXkxT0xhDcnEipCMgc7EBAsIV8nlC7oUwv8-rLMXc_hsu0nbqyH0AXdEBJZ-jz11RRgHBooW9jO2VdWh_cQrMmIlhzg8-enEJJ6Q-ArG9yC-B6GBZivt-4D_26n-tl2d8B2YhIzbkTXb6D-Eza1G8w4kgLBL9lnGB7x2mwqAlUb7RjXyE2JkqDbr21RbI2Vbhjr0f7LPwI1Ww0Tvpsx1A8f3nzf0zB4grA-ODQqXRD5THP9_ghJard9cGi6BUvCxhSuMRH0AwYqt87WOkvhgDsG8MHAT_4Grlwz581rETNcQhrzDGiv8YX1sOnUhxqCq72tR-zBY0zCY7AJwdk-uxiG5_ikwuI9hTfg6j0dbuKINxzSe81SULjCJi-6HfcNPIE5LRowPKgdD0iItP6Fz4YBvLmBecLStF9nPBoqqfcsalJNsSl6J2Fs7qlROxYlgM5QhUqKfhigkocjiyCu1yxncr3uzUeQXWnPFF6sjorleJCB8beqY8ZChbsXh3XBAUwrT__a0LKeaOFlGPwZ0ZQxIKq_I2rHGPB0VuNjgytwapSaEf879MwWP-nKuWnt3oZ6gZ7drtT_v_gH_r_h51MaAAA).

In the following
```python
    with Card(
        margin=0,
        classes=[
            "container node-card",
            "root" if node.is_root else "",
            "mb-5",
        ],
    ):
    ...
```
I shouldn't have to use "mb-5", but I do because the margins in node.css aren't respected. As mentioned, this is resolved if I lift the node.css styles into query.css and remove the `Style` call in node.py. But in general, I'm having quite a bit of difficulty sorting through the CSS order in Solara :(

I did it somewhat quick, so do let me know if you have questions :)

**Comment by maartenbreddels** [comment]
Thanks, this example helped.

Ok, I think we should not have done the margin classes this way, because of the `!important`.
In any case, you can solve this by giving your CSS rule a higher (or same) specificity, by adding an extra CSS class to you css.
```
.v-application .node-card {
  position: relative;
  border: 1px solid #dee2e6 !important;
  margin-bottom: 12px !important;
}
```

This does make it apply, since it now has the same specificity but it comes after vuetify's CSS.
Does this answer your question and solve your problem?

Regards,

Maarten

PS: This is an amazing example, I would love to see this in full context.

**Comment by edan-bainglass** [comment]
Specificity does solve it. I ended up implementing it slightly different, applying instead a `row-gap` to the `node-list` class and a `margin-top` to the `query-controls` class. Avoids having to deal with `margin` directly on the `node-card` class, which was overridden by `v-application`. Works for me. But at least in the future, I'll keep specificity in mind as a last-resort workaround. Thanks :)
