### ISSUE TITLE
`print` to console

### ISSUE THREAD

**Issue by edan-bainglass** [widgetti/solara#738]
If this exists, I'm not seeing it, but in any case, it would be nice if `print` statements would (or could be made to) mimic JS `console.log`.

**Comment by maartenbreddels** [comment]
Hi Edan,

I'm not sure that should be a default, since stdout is expected to be server side, and might contain sensitive information.
I'm curious why you would want this, and what kinda of use case you have in mind!

Regards,

Maarten

**Comment by edan-bainglass** [comment]
Mostly debugging. `console.log`/`print` debugging is common. Would be useful.

The [debugging section on solara.dev](https://solara.dev/documentation/advanced/howto/debugging) is not all that useful/clear unfortunately. I'm on VS code and could not get it to work :(

**Comment by edan-bainglass** [comment]
Okay, disregard. Didn't realize `print` prints to the terminal where the server was launched. All good 👍
