### ISSUE TITLE
Default app layout

### ISSUE THREAD

**Issue by JovanVeljanoski** [widgetti/solara#755]
According to the docs, we can specify a default app layout by creating a `Layout` object in an `__init__.py` file, in the same directory as the main file of the solara app. 

Maybe I am doing something wrong, but this file does not seem to be picked up.
Here is a [pycafe example](https://py.cafe/snippet/solara/v1#c=H4sIAH9vzmYAA51W227cNhD9FUH7kKRYqbrtzYCAtkGBPrQIEKTtQzYwuBJ3xVgiFZKyvQn87z1Dai927LiJFzDA4fDM_Yy-hJWqeXgRrqXoeqVtYFTLNFtL-v3iD3GlcCe5tGtZ823QqI6_fHWxlgH-RpV3_Na-fPHHm79-f_HqG0_ZRg328be__vbm73f0mG6-AXHNtRFKPgqyffFlPF5ejnqXl3feo7XUsM1NUAbv7718S-KXPbNNuQ5_XofT4GixpFCnQcs2vMUlnaJ0Hb6aPg0wmr0PMwpPSP7lIZZvI7qc3cdzohOaO0YZYNbyg491Ekwmk-BdI0xwo_SVCaJgkADo8DywKjCck9IjOZ4ElOU_2Z4qVTWirTWXlOwJORjcCNsc3Py170e90_1DndeqHTpfrZPCw7qtw9eDsapDRATnAnlUuxamh87Ln46O-WDPS-sf_nBxSUJOlD40qszTiD9e7acxv6_ek-BDOA01_zQIzam6BtN8GGLc2H1P8-0lOLO-_0fwm_Biy1rDpyGvhf1dsk0LLasHSPq9bZTEm36valHz6DqJs1mc4rHPTHjx5RB4eJHBuFL2rQLkl4M1jdM0PNQovHh_vLFsY7jF5Y2obRNepLNkGnZC_uuPuT_9wcWugR06ihrPtqLlvwHVcP1aScuE5PoJC6QabbwuVCipkIZ3H-6mj3gxGlqu4myeLopiNZ8XRbaaPen9CRKZjPt9eB_2dH1ektje2icVLy-FFPby0oGde-mzeHAxTZN4kS-z2SzJ89lskTzto4_t-ayOWXouo4dkPp7C5uDfAg49b9NyDTFrnzN60COr9Lubusqiu6EjWUc655kDChCRbMi_WmVPrJJHSO7bFPcMwX0Pvf0vckPwGDpVXVHolDEf3yRomGkugjqZLxOerdJNkaVbtplv6jRfpklRLLPlbLFdSyb3QpVlERdxgpPeKZlF1XYryjLL4_SBMNoIWQu5M7hN4yxOgknQwTopoQfKMo1z98RYq664JD0gp5BYq-k0Ym5YdVWxti1LUIcTcDZYsR1ao4a-IIfSLM4gbzmrmrKcxwmpVThwq1QLrBlsAbniGg_J3wToizjDKx9AGqdgJZwaptGKkVS6Y634zHVZ5nhMiq2orspyCa8WOGH9eY9wVfPNsOv3BIPrY6A1r5RmVgED4ASPRhkMr287F82CRPyWVwhH7ij-hCRbpOSjUdLA_46ROHMBUd2ofuQRvC0g-VRLMupcb9KUQFNXnWbomIT7LjvutaglsHJ6Jvr9FdcS9I9cgY0RAURE1C68OaGNgmjHJbyjHI7Zx8X1AFzE40LyZ6TVhT_a6veg5B23eEb5mkFkVD0gGeB5Sj89huJHbAzn9MqdhPzIMhce-UQ56JVAo7oiOOTzvCCyRZxDNsBXriMUiPYbLCKqM7HScHdG5T4J-TVRKZmen0OAmbCMKOUUyLGQ96-jA52492itowJ2atTvd46m6c41-NndMSkUTYp3HdNXtbpBStCOp2MkLHCOQZN46A3bIg54RgY7ZvtW2VZsIiFbUJ_LosNAml13uRx2wtiBbgkKZ7mpWmaMqFyxzkKkC58-vHRWIVES4UKERp1T48jNluYCEnRc4iTc2IiZvayIGlJkk14qyzdKoVHnSM-ZjVEemUaMw0MQQ-dHJ3M2FExqfCkgSwvUDHA9k7Wq0P3IIqRju_cYVJhMMHHIR89ve17BsSJGKx0t9hhZ8DyG2iVoQZ3Yi7Z1_IMoHXzLLIVVC0Iv_ET3Gl9wtuGDObYV3PX6uOptRMxyJSCnzBZIfG9oUCg1q3h58gArSKuKG9cQPp5BczQgGxmNvN9XFI7vvIyCOzYR6u3msd93rjOwAsCVmCLKRBKv6MZ_WTXW9h7RqeOTyhDFj-PlrLiJrpnl3tMMuaNYvZxGK2rVbufdgLN0tWfEVUSpDvVz9wmXoJizJGvQrqWxJvaDHfpYQVs453M35npb5Xm-ihCzgHkiROpPVJtuVsv5wxvY0oK4PM2BSQg4USWI_Q5m-tq4KcED6BzdMVzWmdVYakdVMPrQj6tgToSEqI24dTPgOtZIgTXgOtgtCr9E3dHRhj8f6eGBeHAL5CDCpArQy3GdGYsFRlkH3kg3EOmWW-uaMne0OnJK7Voa8eAhlsK-MgaEOK5KpMdruEFBiMICxa03sD5w6XOHcvJVnTET6N6sSJbUXVDDvrnXSoVfRoMWYLeORsJRvDMLPgHP5J576HwtwKmoN3xHQGt5w2zV1Aob7H5jOLn70HJ9eU43N5X7Zh_7Fa7fcNBNq9ziL3zNIeLYs-NHBDEtPITQAAEr-jCXVGOv7S9oMJzfI9vie-EQqHeQzBnT4t-nVliOU3j3H79SE_C8EAAA)

The example also shows a way that I figured one can pass a custom Layout that works. 

Do you think this is a bug, or have I wrongly understood or implemented the documentation. 

Thank you.

P.S.: There is also some funny rendering bug of the test app, but I assume that is more of a pycafe thing rather than a solara thing, since it renders correctly locally  - so can be ignored.

**Comment by maartenbreddels** [comment]
That is only the case for a package, so if you run `foo.bar.mypages` orso. In the case of pycafe, we run as `solara run app.py` (we might need to have a configuration for this, because i also would like to demo things like that).

What is your directory structure, and how do you start solara the the command line?

PS: I do recommend the explicit way, i.e. the part below ` This works - uncomment to see`, and we're gonna change the docs to recommend that. Too many people get confused about how the autorouting works (including us).

**Comment by JovanVeljanoski** [comment]
Thank! I was not sure what's the recommended approach - the way the docs are written now looks like the `__init__.py` manner is preferred. 

Passing a layout to `Route` is perfectly fine. 

I also have a package like structure, but not a package that is meant to be installable. The app is also run as `solara run file.py`. It works fine both locally, docker etc..

Thanks
