### ISSUE TITLE
Add a short timeout to `_check_version()` requests call

### ISSUE THREAD

**Issue by ntjess** [widgetti/solara#853]
Some corporate proxies deny access to `pypi.org`. In these cases, `solara run app.py` hangs while it tries to make contact with pypi to check whether its version is up-to-date. Ideally, the call to `requests.get()` occurs with `timeout=1` or something very short & reasonable to prevent inordinate app load times, without requiring an explicit `--no-check-version` (which is unintuitive without debugging)

**Comment by maartenbreddels** [comment]
I agree, that can be very annoying. I think it can be even shorter, max 200ms, because it's fine is we miss it. Do you plan to open a PR for that, or would you rather have us look at it?
