### ISSUE TITLE
[Feature request] Fade or loading overlay for components

### ISSUE THREAD

**Issue by Jhsmit** [widgetti/solara#92]
I have an app with a plotly graph which re-renders when users change some inputs (number of bins, selection of x/y axis, etc)
I'm using the `use_thread` such that the rendering is threaded, and when the redrawing is in progress, the app shows the `solara.SpinnerSolara`. This works well but there are a lot of pixels which change a lot between the loading and rendered state, which makes the app feel very jittery. 

Instead, I would like to be able to place a fade, possible with text / spinner, on top of the previous render of the graph to show the component is loading. Perhaps something similar to or an extension of #81.

**Comment by maartenbreddels** [comment]
As always, good question :)

I have an example that I had let GPT-4 generate, which shows some stock values, and I actually added this fade + progress bar to make this clear:
```python
solara.ProgressLinear(result.state == solara.ResultState.RUNNING)
with solara.Card(f"{State.stock_ticker.value} Share Price", style="opacity: 0.3" if result.state == solara.ResultState.RUNNING else None):
```

**Comment by Jhsmit** [comment]
nice although the current solara 1.12.0 `Card` does not accept style yet

**Comment by maartenbreddels** [comment]
v1.13.0 which is released now does.
