### ISSUE TITLE
dense option for SelectMultiple has no effect

### ISSUE THREAD

**Issue by hkayabilisim** [widgetti/solara#938]
Dense option in SelectMultiple is passed to downstream reacton as always False. Is it because of dense style doesn't make sense for SelectMultiple or it is simply forgotten to set "dense=dense".? In the first case, we should remove dense from SelectMultiple or pass dense to reacton. 

https://github.com/widgetti/solara/blob/071589d0923f1323f09c84cd941b3598e75677f5/solara/components/select.py#L177

**Comment by maartenbreddels** [comment]
Fixed by #939
